### PR TITLE
Census: switch to Sheets approach

### PR DESCRIPTION
**Pull request by abettermap**
Use google sheets as the census attribute source instead of baking it into the spatial.

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela fixed the oil spill and am now using the two 2013-2017 Sheets workbooks directly, so @fiddleHeads might officially be off the hook for census GIS stuff as there are now only two fields in GIS and they never change:

image

So Ross, between those two workbooks and the Languages Config, you should have total control over the census stuff now. Let me know if you run into any problems!

**Comment by abettermap** [comment]
Shoot, I forgot that production is using all the MB fields still, so that's likely breaking right now since I removed them￼. So we should get this merged ASAP as soon as it's been tested a bit￼.

**Comment by rperlin-ela** [comment]
Not sure how much or what kind of testing is needed, but looking at deploy 140 quickly and trying out different census data layers, everything seems to check out

**Comment by abettermap** [comment]
If you're not seeing the black oil spill like we were before when you zoom in close and then turn on the layer, I'd say were good. Merging.￼

**Comment by rperlin-ela** [comment]
Awesome!

**Pull request merged**
