### PR TITLE
SOW3.1.3: minor UI improvements

### LINKED ISSUE #175: Switch Endonym and Language in "Explore" Cards
User suggestion to switch the position of Endonym and Language in the "Explore" cards where they appear together, to match the prominence of Endonym in the Language Profile and in Details. This would not apply to card footers, which are Language only. It would apply at the level of Explore/World Region/Something, Explore/Neighborhood/Something etc. Would also want to have it in Explore/Languages and change "Common language name in English" to something like "Common endonym (used by community) and name in English"

### LINKED ISSUE #188: Standardize font sizes for paragraph-like elements
- [x] “Home” view: World Map text: standardize font size for this and similar UI components.
- [x] “Clear/View Filter” message: follow font size standardization used in World Map text.
- [x] Census popouts
- [x] Census panel
- [x] Language profile panel (not the "read more" intro)
- [x] No comm. selected (related: #183)
- [x] Explore panels' intro (e.g. "Common language name in English" at `/Explore/Language`)
- [ ] Any others?

Some of those might not apply but should really just be able to reuse a single component w/the same color and font size.

### LINKED ISSUE #189: Try new color scheme
Questions:

1. are the primary's the same for all? **YES**
2. are the primary's the same as current? **NO, at least not using the color dropper in Dev Tools. I confirmed that I gave Julia the correct colors via email though, and they haven't changed since then.**
3. are secondaries same for light/dark scenarios? **YES**

Take screenshots of each of these applied to the theme (might just be secondaries depending on above answers):

image

### LINKED ISSUE #190: Color/style/visibility UI improvements
- [x] Census dropdown: make results background black (same as the search box in “Home”)
- [x] Hyperlink: standardize all instances using theme color instead of light blue. **TBD, kind of based on #189. The idea is that all hyperlinks are the same color throughout the app**
- [x] “Details” and “Language profile” views: improve visibility of Audio/Video links by making them more prominent than the surrounding elements, either through a different element type such as a button, positional changes, or simple style adjustments.
- [x] “Share via Email” button: colorize to avoid misconception that the button is disabled.
- [x] Panel “breadcrumbs”: underline links to make their purpose obvious.

Use light green everywhere but do #189 first so we know how it looks.

### LINKED ISSUE #191: Bottom nav panel links: always show text
Bottom navigation panel icons: always show text, not just for the active panel. _Note: this may result in very small text on mobile screens._

### PR DESCRIPTION
**Pull request by abettermap**
## Summary

Got a little sidetracked w/legend stuff but fonts are looking good. Just need deploy for now though...

## Issues resolved by this pull request

- Fixes #175
- Fixes #188
- Fixes #189
- Fixes #190
- Fixes #191

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela looking good and this will wrap up 3.1.3 i believe:

image

**Comment by rperlin-ela** [comment]
Stellar work— looking beautiful. Here's what I got:

- Explore/World Regions/ looks like a little off now with the card changes there, meaning the way the region name and the color dot interact
- Youtube links not working anymore in Video, Archive.org links all ok
- Is the Video button a slightly different blue from everything else? Looks like a little darker in a way that feels inconsistent, rather than making Video pop more— I'd make it the same blue
- I hear you on space concerns for mobile, and we might have to come back to this when we try up-one-level. Might come back to "Read more" too before/when we work on adding that component to the Lg Profile
- I think you're right: double line too much and could be subtler, so do your thing, sounds like you're on it. I'm of two minds on the fancy symbol! It's nifty and elegant, for sure, and I hate to be the buzz-killer, but it may be drawing just a little too much attention to itself. Long day and looking quickly, so maybe I should sleep on it.
- Let's see if we can improve on the text for "Map display options & legend"
- Will respond on breadcrumbs in a bit...

**Comment by abettermap** [comment]
World Region thing happening on all Explore's, maybe result of #175 fix since it's not happening in prod, will look into it.

YouTube links: i haven't done anything with this so i'd suggest opening a new issue. Have you made any changes in AT? The link is working for me in the browser (e.g. [this](https://www.youtube.com/embed/videoseries?list=PLE29ADA7B389607F1)) so let me know if you changed anything (it doesn't look like it from what I can see in Airtable).

Also, did you do anything to your Google APIs token? We stopped using Sheets so just wondering if you dropped the API key or something, which could affect youtube if it's a separate key.

Will fix the vid/audio btn color.

Will try de-doubling and subtlizing the line. If you're still not on board, no worries on the buzzkill, was an experiment in elegance. 🤩 

> Let's see if we can improve on the text for "Map display options & legend"

Yeah I'm not digging it either. I think "Map display options" is so-so for the first part but maybe should mention "languages" somehow? Either way, I just put "legend" in there to save space but it really needs to be down near the actual legend.

Does this stir up any ideas, approval, or rejection?

image

**Comment by abettermap** [comment]
AH, you know what the issue might be with the youtube links? i'm wondering if your API settings aren't accepting hits from non-prod URLs. This works fine for example: https://languagemap.nyc/details/88

Pretty sure we've been able to visit deploy videos before though, that's how we reviewed it. Anyway it's not working for me locally either so i'm not sure what's up. Maybe hunt down your "allowed URLs" or whatever it's called in your Youtube API settings and screenshot it to me.

**Comment by rperlin-ela** [comment]
Screenshot stirs up some approval — if we can afford the space, that makes sense and looks pretty decent.

Speaking of that blue on the video button, I see now that it’s also being used in the Omnibox dropdown and would change that too. In that dropdown and the Census dropdown, the white line turns green on click — I think maybe it stay white or turn blue. This also applies to the search bar and the lines under the filters in Data.

I’ll check Youtube API settings later in the pm. Definitely haven’t done anything to the Youtube links, the API etc and a you say it works in prod (and links work in browser), and never had a deploy issue with this before.

**Comment by abettermap** [comment]
> Speaking of that blue on the video button, I see now that it’s also being used in the Omnibox dropdown and would change that too. In that dropdown and the Census dropdown, the white line turns green on click — I think maybe it stay white or turn blue. This also applies to the search bar and the lines under the filters in Data.

Good catch(es)! Will fix. All those darker blues are our "secondary" color, needs to be the light version of that.

**Comment by abettermap** [comment]
all right man i gotta call it on this legend stuff, today was supposed to be for 3.1.4 and i haven't started yet. it's kind of an exercise in futility to try and cram all the stuff we want to see on load on mobile while remaining aesthetically and intuitively sound UI-wise, plus i keep forgetting that i still have to force the Location stuff in there somehow. i really don't want to lose the little bit of World Region legend that we see on mobile, but it's not very doable with all the stuff above, and at the same time not very intuitive to forego all headings for potentially less intuitive things like a bunch of dots and names and hope people know it's a legend, and understand what the controls above it affects.

anyway i think it looks okay as-is despite your opposition to the combined options/legend title. again, i'm not a fan either, but something's gotta give if we're going to indicate Legend-ness, maintain the relationship between that and the symb dropdown, and still have at least one row of World Region dots appear in the legend so mobile users have an actual chance of knowing that there's something below.

i made the other fixes (excluding youtube links, totally different thing) so unless there's an absolute deal-breaker i'd reeeeally like to merge this so i can keep the SOWmentum going, and we can circle back to the legend/home mess once we finish #195 and the Great Location Migration of '21.

**Review by rperlin-ela — APPROVED** [review]
All sounds good to me, let's keep this train movin

**Comment by rperlin-ela** [comment]
Youtube links all good, so I guess it was a deploy issue!

Are the omnibox neighborhood names the same blue as everything else? Might just be my eyes, and against the black

**Comment by abettermap** [comment]
you've sure got an eye for catching those 😃  yeah I'll change it.

hey isn't that the wrong icon?

image

we've been using this for neighbs and "Local":

image

i'm also fine scrapping the icon in there, it's pretty redundant and not consistent with the rest of the UI anyway since it describes Town OR Neighb. 

we're also using the "Local" icon in the table column headings in addition to Neighb-ness. fine i guess but slightly misleading since it applies to Town rows in the table as well.

**Comment by abettermap** [comment]
i know you're not a fan of repetitive icons, not to mention the light text stands out better anyway (not what i have in screenshot), so i'm going to axe the icons from omni!

**Comment by abettermap** [comment]
your addition of borough names also makes it obvious that they're locations (i imagine MOST users have heard the borough names). so icons are even less important in that sense.

**Comment by abettermap** [comment]
cool?

image

**Comment by rperlin-ela** [comment]
Cool, good call

**Comment by rperlin-ela** [comment]
I know we didn’t discuss this (apologies!), but at Explore/Languages, now that we switched Endo and Language, can we change that top text from “Common langauge name in English” to “Common language name in English and in the language itself (endonym)"

**Comment by abettermap** [comment]
YOU can, it's in the Schema table in AT. Just note that it's also used in the card at top-level Explore view, so try to make it sure it semi-applies to both. 

If you want something beyond that, sorry but I'm not going to customize my /Explore/Something intro component just for that. It's not a question of time or SOW either, it's that there are so many tiiiny variations like that between what would otherwise be consistent code, and it's kind of just adding another layer of "weather resistant plywood" (or whatever I called it) to our fragile little code house. 

The right way to do that though would be another column in AT for that level of Explore. Then it's maintainable and data-driven like the rest of the Explore config (except icons, I hardcoded those).

**Comment by rperlin-ela** [comment]
No this is perfect, forgot about that, just changed it, mind blown 🤯

**Comment by abettermap** [comment]
Woo, AT save!

**Comment by abettermap** [comment]
not sure where to ask this but can we axe the icons here too?

image

i imagine i talked/forced you into keeping them but not as necessary w/boroughs now...

**Comment by rperlin-ela** [comment]
Was just thinking about that earlier — axe away!

**Comment by abettermap** [comment]
axed. i wish we had something more for these guys though:

image

pretty sparse and repetitive but it's not really card-worthy with just the Location name. not sure what to do w/those really.

**Comment by rperlin-ela** [comment]
You’re right, I’m open. “View details and show in map” may not be necessary either, especially if they light up blue like other Explore cards. De-card if you think of something better (in Data, we do already have a “View in map” icon aka “Show in map” on hover). If keeping the card, there’s probably not enough room to show a bit of Description, and for now they’re still mostly repetitive anyway. I’d consider putting some other kind of tidbit in there, but I know that’ll be more work!

**Comment by abettermap** [comment]
> If keeping the card, there’s probably not enough room to show a bit of Description

I thought we had that before but axed it since they were so similar to each other? Or is that different now with the instance/lang-level split on descriptions?

**Comment by rperlin-ela** [comment]
Can’t get anything past you, huh? We did try it, and they still are too similar for the most part. I’m gradually making inroads. Let me know if you think this would be easy (on your end) and actually look good...

**Comment by abettermap** [comment]
Easy, just needs... 2-3 more AT columns haha

Not related to this scope in any way though so I'd better stop throwing ideas out there, already added quite a bit of goodies that was pretty gray-area SOW-wise and although we've been steadily cranking this week, there's a lot more on the docket and some monster tasks in there as well. Gotta stay on track but I'd encourage you to make issues for these things. I feel like a broken record saying that, but I spend a LOT of time writing and maintaining GH issues, so it'd be appreciated if you would document your own wishlist stuff like this and the Read More thing. I think they're both legit ideas but I don't want either of them so bad that I'll write up the issue. It's truly the perfect way to document though, will never get lost in the ether!

**Pull request merged**
