### PR TITLE
SOW3.1.4: smaller new feature additions

### LINKED ISSUE #192: “Data” table: include an “Audio” column
“Data” table: include an “Audio” column in the same manner as “Video”.

### LINKED ISSUE #193: “Language profile”: support language-level text (NOT description)
“Language profile” view: support language-level text, independent of the current language-level descriptions in Airtable, and include it in the introductory section in the same style and functionality as that of the “Details” view. This will involve introducing a column in Airtable, similar to current open-text description columns, and consultation will be provided to Ross as needed.

Part of the reason for this is to allow language-level info that is not applicable to the intro "read more" of Details intro.

**STATUS**

Ross already created a new table, just need to knock out the column/s. Jason will consult.

### LINKED ISSUE #194: 3D/2D: don't force, allow setting consistently
Allow toggling between 2D and 3D in the map (on a per-session basis, not stored between sessions) via a button in the map navigation controls, and remove the current functionality of forcing 3D when a community is selected.

Always show the btn too.

### LINKED ISSUE #195: Improve cross-panel interactions
- [x] “Home” search box: make Language group headings linkable to “/Explore/Language/Language Name”. **If this starts looking hard, jump ship. Was just a minor request.**
- [x] Add a toggle near the Census search box to turn off language points using the same functionality as ~“Show by: None”~ **turning on "Hide points and icons"** in the Home panel ~symbology dropdown~.

### LINKED ISSUE #196: On Census language change, zoom to initial extent
On Census language change (either via Census search box or the "Show in map" button of the Census pop-out), zoom the map to the initial default level. Enable this functionality by default, but add a nearby toggle switch to disable this behavior on demand.

**Will need some wording for the toggle.** Ideas/options for terminology:

- "home"
- "full"
- "default"
- "initial"
- "original"

e.g. `Auto-zoom to initial extent` is how my brain wants it since it's not "full". No strong feelings on the others, but I have GIS bias.

### PR DESCRIPTION
**Pull request by abettermap**
## Issues resolved by this pull request

- Fixes #192
- Fixes #193
- Fixes #194
- Fixes #195
- Fixes #196

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela i got a late start today so decided to push on through like the good ol' days, so have a look at the 3 issues i included in this PR so far when you get a chance. there's some quirks with 2D/3D toggle on mobile, i had problems w/that before, so i'll give a fresh look tomorrow but may have to circle back to that another time. it's all definitely working but i just can't get it to center properly on mobile when toggling, and it's very apparent when a popup for selected community is present.

**Comment by rperlin-ela** [comment]
Quick look on desktop before shutting down for the night but all looking good, can commit or wait as you like in the morning.

**Comment by abettermap** [comment]
Thanks, I'll keep plugging away on this branch. I'm trying to get in the habit/convention of

```
"WIP" in the PR title + not assigning you as Reviewer = not ready for primetime yet
```

If no WIP and you're Reviewer, it's ripe for the pickin.

**Comment by abettermap** [comment]
@rperlin-ela all set for review. still would like to punt these until Week 4 if they're of concern:

1. 2D/3D (#194): if popup is present when this button is toggled on mobile, zoom/pan centered properly in the map (it's offset in 3D right now but wasn't before when we just had the "reset pitch" btn)
2. #195 : if you're not seeing it, or if you are and don't feel it's a problem, case closed. or if you want to take the quick and dirty way out, that's simply adjusting text.

**Review by rperlin-ela — APPROVED** [review]
Other than my comment on #196, looks good to go!

**Pull request merged**
