### PR TITLE
Init new (old) layout

### LINKED ISSUE #212: Desktop layout: de-float (again)
Full circle back to the orig suggestion or something similar. No more crippling map offsets.

image

image

### LINKED ISSUE #246: Off-center popup problem on mobile
from #204 and __Originally posted by @abettermap in https://github.com/Language-Mapping/language-map/issues/196#issuecomment-803240561__

### LINKED ISSUE #256: Classic call-to-action (CTA) button
Quoting @abettermap email: "if we bring in my new desktop layout, it could go in the bottom right side where i stuff those other btns. maybe a popout from there with the donate/join wording (via UI Text of course!). using current layout though, i'd probably stuff it at the top of /Info above About. would just be an intro-ish thing like the other panels, followed by a bigger CTA btn (or btns plural if you have a Donate link)."

"Get Involved"? "Support the Work"?

Top of /Info doesn't immediately feel ideal, but definitely not the worst, and maybe good if it's different-looking and button-y...

### LINKED ISSUE #260: Wording changes: nav, menus, titles
- [x] change "Community details" in the timeline breadcrumbs to "Site Details"?
- [x] we generally are capitalizing top-level header text, so maybe also "Map options" > "Map Options"
- [x] change Explore panel title to "Explore ELA Data"?

_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/258#issuecomment-816687378_

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #212 
- Fixes #246 
- Fixes #256 
- Fixes #260

half of #259, didn't have time to look at other half yet. tomorrow will finish #257 and #263 if super fast and easy and try other half of #259. 

# THEN NO MORE SUGGESTIONS

patience threshold met. hopefully the dozens of extras i included will be "enough".

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela had some struggles so haven't touched mobile or tablet yet.

for tablet, just turn your iPad sideways. it looks/feels so much better anyway, there's no clear-cut "win" for portrait tablet layouts with this application, and and you're asking for massive layout changes that are beyond the scope and even my own suggestions (in addition to a large CTA change, also lots of work and not in scope and potential back-and-forth and you just brought it up yesterday), so please keep those things in mind before applying any additional pressure on ipad portrait complaints for the time being and just make an issue like always since it will involve a lot of work.

**Comment by abettermap** [comment]
except for semi-jank on the sidebar animation when it's opened/closed (it's not terrible but not great), it's working well on desktop (_and **landscape** tablet_) so feel free to test.

**Comment by abettermap** [comment]
@rperlin-ela definitely test on every screen size you have. i think i covered the bases but let me know **if i made anything worse than it was before**.

**Comment by abettermap** [comment]
nvm on the #260 not-done-ness, all set.

**Comment by rperlin-ela** [comment]
Pretty great, we're almost there, I can't even imagine all the patient and amazing work that went into this. Hopefully #257, #263, and bits of #259 and #260 won't too bad. More than enough!

Did a quick initial sprint and found these odds and ends:
- On "Desktop" (including iPad landscape), I'm having trouble toggling the Search panel (in Explore). Works like a champ in mobile but maybe because of that, I just get a little gray box in Desktop and panel doesn't appear.
- Call to action looks good in Info, but the links aren't working for me. Is external linking enabled? "Donate" pulls up some random breadcrumbs and panel goes blank. "Write to us" sticks link in the header but panel blank.
- I think on initial load in mobile (after Welcome Screen) I'm not seeing logo or favicon, but just "Search and Display" at the top
- "Explore ELA Data" is justified left, should go center with all other stuff
- Scrolling around Explore, I see the extra space I take it you're allowing for the "scroll-to-top" button but I'm not seeing the button itself
- This can be pure wishlist, but just to get it down: when panel is closed and I use breadcrumbs on mobile, I think I expect panel to open
- As you said, the five on-map tools are a lil big on mobile. 
- Video not working but I think we discovered that's a deploy/API thing, so assuming that'll fix itself

**Comment by abettermap** [comment]
Thanks, good feedback. I won't be able to fix all those things before your meeting in an hour but maybe A couple.

I will definitely look into the search toggle issue, and not sure how yet but the CTA links as well. 

I should have pointed out that I didn't get to the logo stuff on mobile yet. Was still coding around 1:30 AM and just needed a break for the night. On my radar along with explore heading not justified, that will be fixed with the logo.

I know what you mean about the breadcrumbs thing on mobile when the panel is closed, but we decided a long time ago that clicking a point in the map should not open the panel back up, so I treated the breadcrumbs the same way. I am fine with forcing the panel open, but just note that if you want that behavior than it will be for _any_ route change whether via map clicks,￼ or clicking a result in the language search, or breadcrumbs.

Happy to wire that up, I was wondering about it myself every time I use mobile, but I was just sticking to what we decided a while back, although I think there were no strong feelings and it was a small conversation.￼

The map buttons on mobile are the same size they have always been.

Yes the video is a deploy issue. I really think it's some thing in your YouTube API settings but I can't confirm without seeing it.

The back to top button is ruining my life. Not the button itself, but hiding it and scroll. No joke I bet I have spent over two days on trying to make that show in all the scenarios. It has to do with how much vertical space there is, and ironically adding the additional space to the bottom may have been the culprit for making it not work. 

So either we accept the minor inconvenience that you can't scroll back to top when you have super fast scroll momentum￼￼￼￼￼￼ that hits the bottom (all you have to do is scroll back up slightly and down again to get the button back), or we just show the button all the time and not worry about hiding it. I understand the inconvenience and it's annoying to me as well, but this button was never a requirement in the first place and seems exponentially better than not having a button at all, especially with the miles of help and about text on a phone. 

What's weird is that sometimes it does show. Like I just tried now and it shows fine. ￼

Anyway my vote would just be to show it always, and just make it a little bit transparent or something. Not ideal but I'm not going to spend a couple more days trying to figure this out. I'm also fine with how it was as long as it's working for 98% of the scrolling except when there's momentum and you hit the bottom. there's like 600-700 cards on Language panel, how do you dead-end scrolling to the bottom of that??￼￼

**Comment by abettermap** [comment]
image

See? There's that little bastard right now. Sometimes it shows. Soooo frustrating 🤬

**Comment by abettermap** [comment]
And that was on safari on an iPhone￼

**Comment by rperlin-ela** [comment]
> Thanks, good feedback. I won't be able to fix all those things before your meeting in an hour but maybe A couple.

No prob, do your thing, I can also just talk people through some of the things if we aren't merged.

> I know what you mean about the breadcrumbs thing on mobile when the panel is closed, but we decided a long time ago that clicking a point in the map should not open the panel back up, so I treated the breadcrumbs the same way. I am fine with forcing the panel open, but just note that if you want that behavior than it will be for _any_ route change whether via map clicks,￼ or clicking a result in the language search, or breadcrumbs.
> 
> Happy to wire that up, I was wondering about it myself every time I use mobile, but I was just sticking to what we decided a while back, although I think there were no strong feelings and it was a small conversation.￼

Gotcha, that's tricky, since I want to force it open for breadcrumbs and the language search, but not really for map clicks. If all or nothing, I guess might lean towards forcing it open if it's easy for you, but I can see it both ways, no big deal— your call.

> What's weird is that sometimes it does show. Like I just tried now and it shows fine. ￼

Yeah it definitely adds an element of mystery and excitement, like "Where is it? Will it show up today?"

> Anyway my vote would just be to show it always, and just make it a little bit transparent or something. Not ideal but I'm not going to spend a couple more days trying to figure this out. I'm also fine with how it was as long as it's working for 98% of the scrolling except when there's momentum and you hit the bottom. there's like 600-700 cards on Language panel, how do you dead-end scrolling to the bottom of that??￼￼

I'll second your vote to show it always. I'm easy but definitely was seeing it more before you added the space so if nothing else just go back to that. Like you say, that was 98% good.

**Review by rperlin-ela — APPROVED** [review]
Whenever you think it's in decent shape, merge away

**Comment by abettermap** [comment]
> Like you say, that was 98% good.

ha i meant 98% of the vertical-ness was good, as in the btn would show while you're scrolling for all but the very bottom if inertia.

i put it in 24/7. silly on desktop home or any panel, but even last-resort i couldn't get it to only show on _any_ scroll. absolutely incredibly so frustrating and confusing. kljasdjkflasjkldfjklasdkljfasjdklf

panel title bar should be good except didn't do favicon instead of home icon. on the fence, we'll see

hardcoded the CTA stuff for now.

search popout fixed.

> Gotcha, that's tricky, since I want to force it open for breadcrumbs and the language search, but not really for map clicks. 

maybe i should clarify clicks- i meant clicking a point or polygon (to view details in the panel) or clicking empty space (to see No Site Selected), not btn clicks or general panning around. the popups aren't crazy informative w/o the panel so forcing panel open didn't seem terrible.

**Comment by abettermap** [comment]
> so forcing panel open didn't seem terrible.

*_doesn't_ seem terrible (i haven't wired it up yet)

**Comment by abettermap** [comment]
> so forcing panel open didn't seem terrible.

*_doesn't_ seem terrible (i haven't wired it up yet)

**Comment by rperlin-ela** [comment]
Call went well, I think we're in good shape to wrap up shortly and "launch" on Thursday.

Just a few follow-ups:
-I have a pretty wide monitor but I now see a breakpoint for Explore which wasn't there before merge as I make the screen wider, such that the card for Macrocommunities goes on a different line from its icon. I know the whole thing is tricky and that it's good for most sizes, but maybe it was better how it was
-I take it there's no way just to have "scroll-to-top" 24/7 on mobile? I know I seconded you on 24/7, but maybe would just go back to how it was yesterday, working 98%
-I think there may be a new issue with all external links resolving locally. See the "Read more here" at https://languagemap.nyc/Explore/Language/Sicilian/1007 or https://languagemap.nyc/Explore/Language/Wakhi/1205 for examples

**Comment by abettermap** [comment]
Glad the call went well. 

Not to be a broken record but if you have things you want fixed, please create an issue, preferably for each specific unrelated item. I understand the extra few seconds might be an inconvenience on your end, but I just can't keep track of all the things you want me to do via comments, and they get lost like the ones last night. 

Apologies if I'm just bad at GH or project management, but that's what Issues are for and I appreciate the small extra effort, however trivial and tedious it may seem!

**Pull request merged**
