### PR TITLE
Sheets: all in, Census: more bells/whistles

### LINKED ISSUE #136: Short Descriptions on "/Explore/Language" pages
## Description

A note from Dan on something I think we at least touched on before

Now that we have a great sort of landing page for every individual language that includes all its communities (e.g. for Amharic, /Explore/Language/Amharic), is there a way to have a short bit of overview description here that differs from an individual description (e.g. /details/1089). If this is doable, would I just add another column to the spreadsheet (e.g. Overall Description)? It wouldn't be required, and it will take a long time to fill all these in, but it would be great to have the capability.

### LINKED ISSUE #141: Labels indiscernible if too concentrated
## Summary
Not exactly a bug but some of the communities are too tightly packed to show all of them at once at the default zoom level for when a community is selected:

image

3D reset and sans popup for clarity:

image

Can't see individual points until essentially the street block level:

image

## Solutions

1. Spread out the lat/lon in the data, or
1. Make the map zoom in super far when a community is selected

My take: if there are quite a few instances like this then I'd say Solution 2, but if it's mainly just this Glendale area then Solution 1. This is the first time I've noticed so this so maybe it is just Glendale?

### PR DESCRIPTION
**Pull request by abettermap**
## Issues resolved by this pull request

- Closes #136
- Closes #141 
- Several Sentry issues, hopefully

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela made some good progress on #136 and the census triggers here should be working (just a btn for now, chip + popout later):

image

the dropdown doesn't get set, but it didn't before either. will fix.

spent way too much time making the faded Read More background mask, but it's 2020, we have time for masks. this guy has that plus census btn if you want to test both:

https://deploy-preview-143--languagemapping.netlify.app/Explore/Language/Ilocano

let me know if on the right track. i should be able to wrap up the stuff (e.g. chipped census menu) for this view (can we just call it "pre-Details" or something? getting sick of typing /Explore/Language/LangName, ha) tomorrow. will likely save Details and pre-Details Neighborhoods for next branch. lots of Sentry errors lately, need to get the fixes into prod.

**Comment by rperlin-ela** [comment]
Census and masks look great, totally on the right track, just keep on keeping on. Fwiw you’ll see there’s now a bunch more language-level descrips in the Config sheet besides Ilocano

**Comment by abettermap** [comment]
@rperlin-ela the popout stuff from #136 seems to be working like a champ, here's one to test: https://deploy-preview-143--languagemapping.netlify.app/explore/Language/Beneventano

## When can we merge this?

i keep suggesting/adding more and more stuff to this branch, the lines are blurring, but would really like to wrap it up soon (and the SOW for that matter, i think the finish line is in sight). thinking this:

### This branch
Nothing extra unless there are functionality bugs or glaring UI issues to fix.

### Soon-branch
- UI improvements to pre-Details view (the stuff i just pushed), if i can think of any
- Bring in the chips to pre-Details
- Bring in the census chip to Details
- Map popups. Lots of work for minimal reward, but it'd be really nice to be able to click on a tract/puma in the map so i'll get it in there.

### Final (ha) branch
- Neighborhoods stuff we discussed for pre-Details (may happen in soon-branch if map popups are destroying my self-esteem)
- Is that it??

**Comment by abettermap** [comment]
added another tentative one to the "Final" section

**Comment by rperlin-ela** [comment]
> "Related Census Data" doesn't convey the "granularity" or "level" or "source" -ness of what's going on

Right. I don't know if this gets at what you're feeling, but maybe first above we should have The Census Bureau's American Community Survey **(ACS)**, then below

Related ACS Data (PUMA-level): Tibetan

To me, killing "Census options" (whenever's easiest) and having "Set", "Clear" etc right under that or clearly connected with that text will help. Minor, but I'm also more into highlighting the language name, e.g. **Tibetan** over "Related Census Data". I know we discussed before and decided against, but if having the year(s) would help with this concern and it's not hard, I'm down with that, e.g. Related ACS 2014-2018 Data (PUMA-level): **Tibetan**

> ## When can we merge this?
> i keep suggesting/adding more and more stuff to this branch, the lines are blurring, but would really like to wrap it up soon (and the SOW for that matter, i think the finish line is in sight). 

Agreed, don't see any reason not to merge — and the upcoming stuff all sounds on the mark. Finish line in sight!

**Comment by abettermap** [comment]
Sounds good. I'll merge and get all into next branch. I forgot about years but that too. It's so overkill to have a config just for this so I'll likely hardcode for now and try to brainstorm a painless way for you or Matt to update without recruiting Future Jason to change one line of code. 

Let's dedicate next branch to pre-Details wrap-up.

**Comment by abettermap** [comment]
Btw if you're on iOS I highly recommend the GitHub app, it's excellent

**Pull request merged**
