### PR TITLE
Video/media: add metadata to modals

### LINKED ISSUE #72: Add audio/video metadata
## Description

We'd like to import metadata automatically from Youtube and/or Archive.org and show it under the language name above the audio/video embed in the dialog. Probably the most important thing would be what both Youtube and Archive.org call the Description, but maybe a few other fields like rights, attribution. We also have this info in spreadsheet form if that’s easier.

## Resolution

@abettermap thinks Youtube may have an API we can use

### PR DESCRIPTION
**Pull request by abettermap**
Closes #72

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela 

The metadata (and embed from before) are wired up for individual YouTube vids if you want to test it out: http://deploy-preview-116--languagemapping.netlify.app/

YT playlists and Archive are all kinds of broken but I'm not stuck, just spent for the night, I should be able to wrap it up tomorrow though.

**Comment by abettermap** [comment]
Ross-

here's most recent deploy (same url): https://deploy-preview-116--languagemapping.netlify.app/

let me know if i missed anything in here or #72

**Comment by abettermap** [comment]
@rperlin-ela all good?

https://deploy-preview-116--languagemapping.netlify.app/

**Comment by rperlin-ela** [comment]
all good

**Pull request merged**
