### PR TITLE
Table: support export to CSV, PDF

### PR DESCRIPTION
**Pull request by abettermap**
Working for PDF and CSV, albeit sans Endo's for the ones that can't hang with Gentium Plus.

TODO:

- text not numbers for "Size"

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela decent progress if you want to take a look: https://deploy-preview-117--languagemapping.netlify.app/

The TODOs I mentioned in #93 comments: likely tomorrow.

**Comment by abettermap** [comment]
@rperlin-ela ok i think we're in pretty good shape here: https://deploy-preview-117--languagemapping.netlify.app/

If there's anything minor missing, or anything major broken, let me know. For more bells n whistles, please create a new issue.

This one takes first and second place for the October Surprise Challenging Rabbit Hole Award 🏆

**Comment by abettermap** [comment]
Things to check:

* [ ] CSV exports work
* [ ] PDF exports work
* [ ] On mobile
* [ ] And desktop
* [ ] Aside from "missing" Endos, all is well enough
* [ ] In-PDF link to source spreadsheet works
* [ ] Table layout and style are legible. No mid-word line breaks.

**Comment by rperlin-ela** [comment]
Everything totally checks out. Congrats on the Award, maybe there won't be even be a third-place finisher. Some people may have pop-up blockers and not realize it, but I'm not sure there's anything to do about that. Agreed about slipping in a little "Not all endonym scripts supported by PDF export" note, probably just on the PDF itself?

**Comment by abettermap** [comment]
Sounds good. I’d like to wrap up this branch though so let’s do a new issue for smaller export improvements like that as I’m sure there will be other suggestions, e.g. I wouldn’t mind a “Showing X of Y total records” so that the export will more clearly indicate that it’s only a subset of the full set.

**Comment by abettermap** [comment]
Oh and yes to the popup blockers. That’s going to be a browser-specific thing we can’t control. It’s not an issue to me since it only happens once and it’s obvious what caused it since it happens immediately after the click.

**Comment by abettermap** [comment]
I created the issue here, feel free to add as needed 

https://github.com/Language-Mapping/language-map/issues/118

**Pull request merged**
