### PR TITLE
Improve Neighborhood Explore panels

### LINKED ISSUE #225: Remaning Neighborhood tasks
(from #222)

- [x] move toggle out of Search Locations into /Explore/Neighborhood and one level deeper
- [x] for /Explore/Neighborhood/Something with no primary langs (???), rm the preceding text before where the cards would normally be.
- [x] support intro text from summary field in AT
- [x] show borough as subtitle in /Explore/Neighb/Something

## Later
(moving to new issue)

- support auto zoom on initial page load when starting from something like /Explore/Neighborhood/Astoria.
- Share btns if we have to (???). Was my idea in the SOW, but we've also added 1k tasks to it, so my vote is making it optional in favor of the other massive tasks i created for myself. Not to mention it's kinda useless unless i fix the auto-zoom on load.

### LINKED ISSUE #228: Restore Gentium
I added some checks to remove fonts during local development but looks like it slipped into other environments somehow. Just need to restore so the fonts look right…￼

### LINKED ISSUE #235: Share text from Language Profile is "undefined"
I think I caught an instance of this before, but now I see the pattern. Clicking Share from any Language Profile works great except that the first word of the share text (which should just be the language name) is not getting picked up and comes out as "undefined"

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #228
- Fixes #225
- Fixes #235 

More or less decoupled all the /Explore/Neighborhood routes from that level to the first child, and left the language profile view intact.

### CODE REVIEW

**Comment by abettermap** [comment]
shoot, i broke this level

image

might have to get at it in the morning, need a walk bad!

**Comment by rperlin-ela** [comment]
Hot stuff on #225. Just made a few comments in that issue.

Not sure about if I see #228 — it might be Gentium but the main Descrip text still looks different than it looked before.

Get out on that walk!

**Comment by abettermap** [comment]
> Sure, give the Neighborhood Profiles an escape hatch to Explore/Neighborhoods, I feel you. 

Are we thinking stacky? Like a line below the layer toggle? Or alongside it and with the style of our De-select button in Details? And should that be the button/link wording or something else?

> Yeah, I think I can just do some wordsmithing on the Holliswood-like nabes that have secondaries but no primaries, don’t think they need any special treatment from you. 

As in change the wording of the generic "additional locations" heading before its list, or the summary in the intro? I'd rather not do a conditional check in the former, and you have control over both, so wordsmith away. 

> Can I easily get or do I already happen to have internal linkability for that “summary” text too? 

I believe so. I think the only ones I robbed you of as far as linkability goes are the search box placeholders. 

> I do kind of feel like we over-axed the "Show neighborhoods” toggle and need it somewhere a little more prominent. Can’t remember if that’s still in the cards. At least Explore/Neighborhoods itself? Now it’s pretty much only if you find your way to Explore/Nabe/Something, right? And someone might turn it while they’re checking out a Neighborhood and not know where to go turn it off.

Good point. I can add it to /Explore/Neighborhood but I don't think that'll be enough. Honestly the best spot was probably below the Search Locations box, at least with the current UI. 

The other alternatives I could think of are so-so but it's gonna be buried no matter what:

- A third tab after Search Locations. It would be swipeable on mobile, not "all three tabs at once" kinda thing. And if it doesn't fit on desktop then I think there's a scroll arrow thing. But seems like it would fit if we call it something short like Map Tools. It would be the true dumping ground, and also include the "zoom to my location" and counties toggle.
- another button below the 2d/3D button, like we discussed. Again, buried, and I feel like it's an even crappier option since it's visible 24/7 for things that don't need to be accessed that often. Fine on desktop i guess, but seems like overkill on the right side of mobile.
- ??? I'm sure there's other options. Maybe after the legend? Haha I don't know. I componentized the toggle though, so it's like 2 lines of code to sprinkle it into anywhere in the app.

**Comment by abettermap** [comment]
As for these...

> Hot stuff on #225. Just made a few comments in that issue.

Not seeing it. Or was it just the "i" button thing? That's the most recent comment I see on that issue. 

> Not sure about if I see #228 — it might be Gentium but the main Descrip text still looks different than it looked before.

Dammit. I undid the stuff but yeah you're right it's a different font. Gotta be something simple.

**Comment by abettermap** [comment]
Not sure if you've run into this yet but I'll get on it tomorrow. 

image

https://deploy-preview-233--languagemapping.netlify.app/Explore/Neighborhood/Downtown

**Comment by abettermap** [comment]
Oh and here's the scrollable tabs thing I was suggesting. Haven't tried on desktop but plenty smoove on mobile. 

https://material-ui.com/components/tabs/#automatic-scroll-buttons

**Comment by rperlin-ela** [comment]
> Not seeing it. Or was it just the "i" button thing? That's the most recent comment I see on that issue.

My bad, I actually made the comments here. You've already responded to them here below.

> > Sure, give the Neighborhood Profiles an escape hatch to Explore/Neighborhoods, I feel you.
> 
> Are we thinking stacky? Like a line below the layer toggle? Or alongside it and with the style of our De-select button in Details? And should that be the button/link wording or something else?

I think alongside it and with the style of our De-select button in Details, but you do you.

> As in change the wording of the generic "additional locations" heading before its list, or the summary in the intro? I'd rather not do a conditional check in the former, and you have control over both, so wordsmith away.

The latter I think, should be nothing for you to worry about

> > I do kind of feel like we over-axed the "Show neighborhoods” toggle and need it somewhere a little more prominent. Can’t remember if that’s still in the cards. At least Explore/Neighborhoods itself? Now it’s pretty much only if you find your way to Explore/Nabe/Something, right? And someone might turn it while they’re checking out a Neighborhood and not know where to go turn it off.
> 
> Good point. I can add it to /Explore/Neighborhood but I don't think that'll be enough. Honestly the best spot was probably below the Search Locations box, at least with the current UI.
> 
> The other alternatives I could think of are so-so but it's gonna be buried no matter what:
 
> * A third tab after Search Locations. It would be swipeable on mobile, not "all three tabs at once" kinda thing. And if it doesn't fit on desktop then I think there's a scroll arrow thing. But seems like it would fit if we call it something short like Map Tools. It would be the true dumping ground, and also include the "zoom to my location" and counties toggle.
> * another button below the 2d/3D button, like we discussed. Again, buried, and I feel like it's an even crappier option since it's visible 24/7 for things that don't need to be accessed that often. Fine on desktop i guess, but seems like overkill on the right side of mobile.
> * ??? I'm sure there's other options. Maybe after the legend? Haha I don't know. I componentized the toggle though, so it's like 2 lines of code to sprinkle it into anywhere in the app.

Ok, /Explore/Neigborhood for sure. And it can always go back to its former spot below the Search Locations box. The "third tab" option is a little bit intriguing since you were always touting the power of three over there and maybe it would look very clean to have that dumping ground. If you're up for trying!

**Comment by rperlin-ela** [comment]
> Not sure if you've run into this yet but I'll get on it tomorrow.
> 
> image
> 
> https://deploy-preview-233--languagemapping.netlify.app/Explore/Neighborhood/Downtown

Good catch, my bad, I actually think with borough wired up the name is fine as is (in Mapbox, presumably), so I made the change in AT and now I think it's fine.

**Comment by abettermap** [comment]
> The "third tab" option is a little bit intriguing since you were always touting the power of three over there and maybe it would look very clean to have that dumping ground. If you're up for trying!

I am if I'm right about it being a quick yay or nay. It's either going to fit with "Map Tools" as the tab label on desktop, and feel intuitive on mobile, or it's not. Don't want to fart around with any styling. "Out of the box" defaults from the Material plugin or nada.

**Comment by abettermap** [comment]
> > Not sure if you've run into this yet but I'll get on it tomorrow.
> 
> > 
> 
> > image
> 
> > 
> 
> > https://deploy-preview-233--languagemapping.netlify.app/Explore/Neighborhood/Downtown
> 
> 
> 
> Good catch, my bad, I actually think with borough wired up the name is fine as is (in Mapbox, presumably), so I made the change in AT and now I think it's fine.

Yep looks good, whew!

**Comment by abettermap** [comment]
## toggle at /Explore/Neighb
neither one is stellar, which one sucks less?

image

image

also, can we say `Show neighborhoods in map` so it's clear that we're not hiding the list below the toggle?

## clear neighbs
speaking of which one sucks less, which of these beauties you want?

image

image

or maybe we've been barking up the wrong tree?

image

it's not as prominent w/longer names:

image

either way, would it get confused with the "X" behavior? and if user does click X, is it ok they lose their clear-ability? (i don't think we need it in popup _and_ panel)

**Comment by abettermap** [comment]
getting pretty meaty on mobile though

image

**Comment by rperlin-ela** [comment]
I’m not sure, defer to you, but maybe toggle below (option 2), and “in map” is good.

If we made the move to De-select elsewhere, let’s stick with that. Do we need it on the pop-up? I agree that’s confusing. In the panel it works, and maybe the action can be equivalent to the “x” in the pop-up, but sorry if I missed a beat.

**Comment by abettermap** [comment]
> Do we need it on the pop-up? 

not if it's in the panel. was just an alternative.

>  maybe the action can be equivalent to the “x” in the pop-up, but sorry if I missed a beat

you mean equivalent to X if we do the link in the popup, right? not the panel? panel we decided "de-select" would take you up a level to /Explore/Neighborhood. i think it's moot though, panel is fine.

is left side any better than centered?

image

**Comment by rperlin-ela** [comment]
Yeah all sounds good. Not sure if left or center is better, both might be ok, your call!

**Comment by abettermap** [comment]
so with the Share btn there's a bit too much going on in mobile. ideally everything fits on one line like it does on desktop, but it wraps too much on mobile, but since this is a low priority i'd like to do something generic, so either:

image

or

image

or with a bunch of styling tweaks, could conceivably get on one line:

image

keep in mind the menu opens below:

image

**Comment by rperlin-ela** [comment]
Totally good — I’m fine with squeezing on one line if possible

**Comment by abettermap** [comment]
so are all these controls going **above or below** the summary?

and do you want wrapped like this

image

or back to previous text and just assume they'll figure it out when they click the button? 

image

**Comment by rperlin-ela** [comment]
Ok, maybe we don’t need “in map” so much if it doesn’t quite fix. Below summary seems right

**Comment by abettermap** [comment]
wowwww spent way to much time on that. definitely give it a look on mobile though. it wouldn't even fit on one line after removing the "Share" text without also hiding the "in map". so smallllllll

anyway we have to finish this friggin branch so please review asap. then i'll start bringing in counties. 

make sure to review anything to do with intros in the /Explore/just-about-anything. it's hard to juggle the vertical spacing on certain bits when the stuff below them doesn't occur in all views. 

test the #235 thing too please

**Review by rperlin-ela — APPROVED** [review]

**Comment by rperlin-ela** [comment]
Strange, Neighborhoods toggle text now looks like "Show neighborhoodsin map" on desktop, but before (or when I copy the text) I can tell the space is there. Again, I think it's fine just to cut "in map"

**Comment by abettermap** [comment]
shoot i fixed that, then broke it. it's suppose to preserve the space. will get it in the next branch.

**Pull request merged**
