### PR TITLE
Most of SOW3.Week2

### LINKED ISSUE #182: Details: nest into Language route hierarchy
## Description

Cart before horse but this will determine some large aspects of SOW3 so let's discuss here...

The request is to remove Details from its own devoted nav level and nest it into the hierarchy. In tandem, include a Back-like ("up one level" to be specific) button or link in the top left of the Details panel. This is pretty standard in mobile apps and makes sense here. For consistency, the button/link would need to be included in other panels as well.

## Initial prototypes

Would we want to double-up on the language name here or rely on just the breadcrumb like this?

image

I'm kind of digging the double-up myself, as long as the sub-heading is subtle in color:

image

Use same format for other panel levels as well:

image

## Implications
...may be far reaching. Let's think it through.

### Routing
At a glance there are about 3 dozen instances in the code where `/details` things occur. 

Proposed new routes:

1. https://languagemap.nyc/Language/Peruvian%20Quechua/719 **OR**
2. https://languagemap.nyc/Language/Peruvian%20Quechua/details/719

Item 2 would allow the next issue to be addressed.

### "Try one at random" btn
Would this path be the "new empty details"? Basically anything that matches the `/Language/LangName/details` pattern.

https://languagemap.nyc/Language/Peruvian%20Quechua/details

### Super-long language names
e.g. `Caribbean Hindustani` would take up a lot of the "up one level" space and there are certainly others which are longer. Just leave enough room above the Endo I guess?

### Breadcrumbs
Would it be as simple as this?

image

"Simple" as in UI-simple. This will/would be quite a potential nightmare in the code.

### Anything else
Tons of moving parts. What are we missing?

### LINKED ISSUE #200: Nested panels: add "Back" up-one-level button
## Jason edits

~~Breadcrumbs: adapt text and format it to the new structure of the nested Details view.~~ droppin' the crumbs, Boss. we've got enough on split btn and timeline below in thread, let's use that as guidelines for this:

> Implement "Up one level" functionality through a button or link in the top-left corner of all nested panels. For example, “/Explore/Neighborhood” would link to “/Explore”, “/info/about” would link to “/info”, and “/Explore/Language/Dzongkha” would link to “/Explore/Language”. This will serve as a useful supplement to the semi-obscure functionality of the panel title breadcrumbs.

### LINKED ISSUE #205: Feedback form at "Details" and "Language profile"
Create a prominent link to the feedback form at bottom of the “Details” and “Language profile” views using a style button or prominent link element, and add basic supplemental text if needed.

In terms of the latter, some disclaimer like the following would be ideal:

"Note that [Lang Name] may be spoken throughout the New York area — this is just one significant location. Submit your feedback." (where the second bit could be in button form?)

### LINKED ISSUE #206: Census panel: dedicate to... census
- [x] Break up the “Local” panel
- [x] rename it to “Census”
- [x] use the same icon as that of the Census pop-out menu (“FaClipboard”).
- [x] Move the “Location tools” controls into the “Home” view, and allow their visibility to be set through a toggle or other navigation component (see below). Consideration will be made to emphasize the current search-by-location feature through both wording changes (“Location tools” is not sufficient) and UI decisions so that it will not appear too “secondary” to the current “Search language communities” search box.
- [ ] might as well do this in this issue too since it will contain the toggle for the Search tabs: “Home” search box: improve access to this feature by cloning it into a pop-out menu that can be triggered by a clickable icon located in the right side of the panel title bar (where the help and about buttons currently reside).

Super related: #202 . We're going deep with the routing, all in!

As for the Location Tools, that's likely heading into a `...` menu in top right, and the "search locations" grouped w/omnibox into tabs:

image

the tabs and their content will be toggled by the Search btn icon on the title bar. this pretty much covers the layout: https://l46ly.csb.app/

### LINKED ISSUE #208: Restructure routes and fifth panel
## Summary

This is a monster, but they're all related so it's gotta be one issue...

- [x] Off-canvas sidebar: migrate contents into a new panel (the fifth panel, which “Details” currently occupies) named "Info". Remove top-right About and Help buttons from the panel toolbar.
- [x] In tandem with the sidebar migration, create nested views (one level of depth only, no sub-views) for help, about, and the feedback form. This content will be nested into the second level of the Info panel rather than the current approach of modal dialogs, which will allow users to see the map while they read Help content, and presumably resolve issues related to closing modal dialogs.
- [ ] Nest “Details” view into `/Explore/Language/Language-Name`: rather than devoting an entire permanent panel view to Details (with its own bottom nav tab like we have now), set up URL routes for this info as a child of /Language/Language-Name and remove top-level direct access from the bottom navigation bar.
- [ ] “No community selected” scenario: adapt this to the new nested Details setup and ensure that it is linkable throughout the application, possibly through a dedicated URL such as one with a “no-selection” suffix as an alternative to “details” being in the URL, e.g. `/Explore/Language/no-selection`.

make sure #200 works with all these instances once they're ready. probably best to do this Restructure issue before 200...

### LINKED ISSUE #209: Link/s to "Intro" video or help doc PDF
This one has been super up-in-air but I think most recent decision was PDF link for now?

- [x] "Intro" video: add CSS support for WordPress (WP)-driven content, which is currently Welcome, Help, and About modal dialogs. Provide Ross with HTML structure and consulting as needed. Note that this task may be removed in favor of a simple link to a static PDF manual.
- [x] "Intro" video: include the video at the top of the new "Info" panel using an iframe from YouTube. Address the in-progress status as needed since the video has not yet been created. Note that this task may be adjusted in favor of a simple link to a static PDF manual. In that event, the link will still be included in the requested position where the video would have been placed.

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #182
- Fixes #200
- Fixes #205
- Fixes #206
- Fixes #208
- Fixes #209

### CODE REVIEW

**Comment by abettermap** [comment]
pushed up what i have so far, functionality is there and i'm regretting ever suggesting the search icon in the top bar, lost an afternoon, so much for finishing on time 🤷‍♂️

**Comment by abettermap** [comment]
obviously still 10000000 design changes to make so probably hold off on that.

at least there's both the popout for search tabs as well as in-panel search tabs in Home, so if one sucks less than the other then we can use that version for non-Home search tabs

**Comment by abettermap** [comment]
@rperlin-ela Any opinions leaning one way or another so far based on what I pushed up regarding putting the non-home search tabs into a popout versus at the top of the panel like we have on Home? Or get rid of it entirely? 

If we do keep it and decide to put it in the popout then ￼I'll make the￼ popout open to the left on desktop, it's just using defaults to the right for now.￼

**Comment by abettermap** [comment]
I'm thinking if we do keep it in the non-home panels then it might be better putting it in the same place that it is in the home panel instead of a popout. Then I don't have to do any special styling, and just show/hide it when the search button is clicked.

I'm pretty much giving up on trying to show any of the legend in the first view on mobile, totally futile effort. We just have so much stuff crammed into that home panel now that I've lost hope that seeing some actual colors that mean something in the first view going to happen. I try to pretend I am a designer once in a while, but there's a reason why you only see "developer" in my job title!

Not the end of the world I guess but even though you're not viewing this on mobile often, there's unfortunately a substantial amount of users on who are statistically going to be on smartphones and they might not stick around if they don't know what the 20+ dots mean on load. 

Not sure what to do about it, but on a positive note if I totally give up on showing what I think is important then I can at least show it in a way that's comfortable and not crammed in for the sake of instant scroll-free legend interpretation on a phone.

**Comment by rperlin-ela** [comment]
Very nifty stuff. Pop-in instead of pop-out seems fine given how sleek and slender it is. The only panel I worry a little about is Census, where it could be a little confusing to see the search under a Census header. But maybe there’s a way to design or word our way around that. I’ll also try to cut down the text associated with “Search Locations”. It doesn’t need Location tools as a header, I think. And I can reduce “Enter an address…”

You’ve been fighting a legendary fight for that bit of legend. I still just barely see it on my iPhone XR (ancient, I guess?), and like I said I think it’s enough to see a bit of it on the "Search Languages” tab and not the other. If you want to keep fighting the noble fight, I’m open to ideas — I know we need it elsewhere, but on Home the green bar at the top feels a little redundant right now. Maybe we could also put “Enter a language…” inside the search bar, replacing “Search language communities” or combine to make it “Search languages, Glottocodes, ISO 639-3”? (In a pinch I don’t think we really need to say endonym here.)

Anyway looking real good!

**Comment by rperlin-ela** [comment]
I know it’s not a dropdown, but I wonder if it would be nice and not too hard to make the Location search bar match the sweet new Language search bar? Just thinking about parallelisms now

Likewise, maybe time has worn me down, but instead of “Enter an address…”, I could see just having this text instead the location search bar: “Enter any location within metro NYC, e.g. Astoria, Bronx, Times Square” — or whatever like that will fit

**Comment by rperlin-ela** [comment]
Yeah still thinking about it, I like parallel text:

“Enter a language, endonym, Glottocode, or ISO 639-3” inside the Search Languages Bar, and
“Enter a location within metro NYC, e.g. Astoria, Bronx, Times Square” inside Search Locations

Last for tonight— maybe I’ve now come around, if you’re still into it, to having the search icon on Home after all. And if someone clicks it they would just be hiding the search panel. Not important, just mentioning. So it would be the same as other panels but open by default on Home. Sorry it took me a while to see the light

**Comment by abettermap** [comment]
Good feedback, I'm on board with most of this or at least some flavor of it, but pretty heavy UI discussion so let's Zoom tomorrow if you are available.

I got the current sidebar nav/off-canvas stuff out of there and the help and about out of the modals and into an Info panel in like an hour, so that was a nice win after the cripplings of everything else today. 🏅

**Comment by rperlin-ela** [comment]
Super cool, I'm loving the new Info. Kind of like Tuesday, I should be good to Zoom starting in a few hours, for a few hours— will drop you a line

**Comment by abettermap** [comment]
Zoom sounds good, hit me up in a few hours. replies to yours:

> Pop-in instead of pop-out seems fine given how sleek and slender it is. 

just to confirm, you mean put it in the panel, like on Home, right?

> The only panel I worry a little about is Census, where it could be a little confusing to see the search under a Census header. 

oh i see, like they would think they are searching census languages?

> But maybe there’s a way to design or word our way around that. 

wording i imagine, as long as it's consistent in all instances of the search tabs, don't want to go down the dynamic road there.

> I’ll also try to cut down the text associated with “Search Locations”. 

i feel like geosearch is a pretty common tool, so yeah it could be pretty slim. the only thing it doesn't include is counties, which are now creeping their way into the app, so might want a disclaimer like "does not include counties". also i disagree with the concern to specify that it's only for NYC. there are a LOT of cues in the app that it's about new york, so if people are looking for stuff in Wyoming then that's kinda on them.

> It doesn’t need Location tools as a header, I think. 

good call, forgot to take that out.

> And I can reduce “Enter an address…”

honestly i think we could almost scrap that. like i said, geosearch is pretty common, don't need to go overboard describing it. i do like your curated examples for Staten Island, etc., but i think something generic there instead of the "Enter an address…” above would cover it.

> I still just barely see it on my iPhone XR (ancient, I guess?)

ha, if so then mine is too. been rocking the X since it came out. rarely ever screws up, love love love it.

> but on Home the green bar at the top feels a little redundant right now. Maybe we could also put “Enter a language…” inside the search bar, replacing “Search language communities” or combine to make it “Search languages, Glottocodes, ISO 639-3”?

in the bar itself or below? eventually stuff will be truncated in the bar if it's too long. i tried reducing font size but there's a bug in iOS where it forces your screen to zoom in if form input text is too small. but yeah the glotto et al is important to indicate somewhere. 

> (In a pinch I don’t think we really need to say endonym here.)

yeah i don't know how many people will search for that since the rest of the app is in english/roman chars. i'm fine dropping it, but if we do then might as well not make it searchable by Endo too? otherwise it might trigger some surprise results. i don't think we should be using endo in the first place since it's not shown in results. so there's 2 good reasons to drop it.

> I know it’s not a dropdown, but I wonder if it would be nice and not too hard to make the Location search bar match the sweet new Language search bar? 

nice: yes. 100% agree. not too hard: no. it's MB's plugin, has its own style and everything, and i've fought it a bit already just to make minor tweaks. in order to full-on make it match our omni, i'd say half a day up to a day's work since it would have to be entirely rewritten to use only the MB API and hand-roll the search box myself. hard No on that one but feel free to add an issue, although i know that is unlikely so i'll just stop suggesting it and also stop creating them for your ideas. sorry, too tedious!

> Likewise, maybe time has worn me down, but instead of “Enter an address…”, I could see just having this text instead the location search bar: “Enter any location within metro NYC, e.g. Astoria, Bronx, Times Square” — or whatever like that will fit

maybe half of that would fit?

> Yeah still thinking about it, I like parallel text:
> “Enter a language, endonym, Glottocode, or ISO 639-3” inside the Search Languages Bar

unlikely that will fit. drop endo, maybe. doubtful on mobile tho. 

> “Enter a location within metro NYC, e.g. Astoria, Bronx, Times Square” inside Search Locations

inside the bar itself? maaaaybe half of that would fit. we're looking at the same thing right? you can count that characters of the current stuff and pretty much determine it from there.

> having the search icon on Home after all. And if someone clicks it they would just be hiding the search panel. So it would be the same as other panels but open by default on Home. 

so what happens when they close it on home? does the view they go to next have it closed too regardless of home? does it retain the last state it was in on a non-Home view? should it always be closed initially when a new view is visited? what if they open it and go back to Home and Home was open last? 

this is getting super complicated so let's dial it in on zoom.

**Comment by rperlin-ela** [comment]
> Zoom sounds good, hit me up in a few hours. replies to yours:

Ok, don't reply to this. We'll deal with any loose ends on Zoom

> just to confirm, you mean put it in the panel, like on Home, right?

Yes

> oh i see, like they would think they are searching census languages?

Yes, this is already a real source of confusion. But yes I understand about consistency.

> i feel like geosearch is a pretty common tool, so yeah it could be pretty slim. 

Ok, we're clearly more or less in agreement, but a few sticking points. I'm totally fine dropping mention of endo (because it's really another specific way of saying language, _your language_) but not dropping the search ability, which I think is pretty essential. I don't see there being many confusing results-- it just wouldn't be super-narrow. On the other hand I don't think the county thing is worth a disclaimer. 

So here was my first shot at text, and I don't see there being any other text besides this in the search panel. I put shorter examples to make it fit better, but if the current ones fit it's fine to keep those.

“Enter language, Glottocode, ISO" inside the Search Languages Bar, and
“Enter location, e.g. Bronx, Astoria, 11385” inside Search Locations

but I think it might also be possible to go purely "e.g.", leaving Location intact and putting this for language:
"e.g. Mixtec, 台山话, hait1244, loy". Regular users might be confused but actual users of Glottocodes and ISO codes would probably get it.

I didn't totally understand your response about matching search bars, but I saw "half-day" and "hard no", so nothing more to say. Maybe this is part of what you tried to address, but now that we're going nuclear about space, I do think that white Location search bar has big margins and eats a lot of precious space, and the font on "e.g..." could be a bit smaller. I don't mind the end of "Stadium" getting cut off on mobile.

> so what happens when they close it on home? does the view they go to next have it closed too regardless of home? does it retain the last state it was in on a non-Home view? should it always be closed initially when a new view is visited? what if they open it and go back to Home and Home was open last?

Just a suggestion, definitely don't have to do it. I imagine the same thing would happen with it that would happen elsewhere, only difference that here it's open at first. And I can't remember for sure, but I think we said this whole thing (at least back when it was a pop-out) was going to be panel-specific, so opening or closing it in one place wouldn't open it everywhere, right?

**Comment by abettermap** [comment]
made some more progress, should be ready for review-ish:

- timeline ready 
- Back btn has been ungrouped and de-texted
- search tabs text (would like a more non-linguist-friendly language than Mixtec though!)
- and style is pretty close
- search icon in top panel bar now only shown in /Explore and its children
- pdf Manual link
- if you don't hate Data table icon in bottom nav let's keep it. i just like its former one better as the timeline trigger btn
- the "loading after you leave the window and come back" should happen far less often for WP stuff now

not yet:

- new details routes or stuff like that
- centered panel title (haven't ready your reply yet, will tomorrow)
- anything census
- anything w/the styling of the search boxes in the search tabs. might take some work to get Material's search input background to white.
- smooth animated toggle of search tabs

**Comment by rperlin-ela** [comment]
This train is mooovin, and who am I to get in the way? From a quick look on Desktop, all these things are working nicely so I’d say for now just keep on keeping on

**Comment by abettermap** [comment]
Got another language that's less obscure than Mixtec yet still interesting and semi-familiar as a language for Johnny Average User like myself? Mixtec makes me think of an electronic music genre.

**Comment by rperlin-ela** [comment]
And a good genre it would be. But I’m feeling pretty good about Mixtec here, because it’s an important and interesting one in NYC, it’s short, and it gets people into the spirit of the map, and it does say Search Languages right above so I think people will get it. If we try to choose one that Johnny has heard of, it’s going to be pretty boring and limited. We’re just saying “Try…"

**Comment by abettermap** [comment]
fair enough, although i don't actually notice the "search languages" text, and it's so much more subtle than the bar below that i don't really make the connection that it applies to Mixtec and certainly not to the endo, glotto, or iso. those only add to the confusion about what the box does for me.

i know you're in Minimal Ross mode lately, but would really like to get our helper text back below the box if you're not opposed. we can leave out endo if that helps.

**Comment by rperlin-ela** [comment]
I think I like where we’re at— how would you want to do it? Top line, even if it’s a little backgroundy, tells people to “search", second line tells people to "try”, so I don't think we want a third line telling people to “enter”, when it’s all for the same thing. If anything I think it would be more useful on Location, but there it would get even busier with the three toggles. If your main worry is that “Mixtec etc” is too mysterious for people and that some familiar language name would clinch it, I could see axing Glotto or ISO (let the cognoscenti figure it out) for something like this: “Try Irish, Mixtec, 台山话”. Thai instead of Irish? But we’ve got to signal and live up to this being a map focused on less common languages. Does that help?

**Comment by abettermap** [comment]
> how would you want to do it?

i would just put the same very-small line _below_ the box like we had before, but sans endonym and make it not verby (no try, enter, etc.), just a definition of what the box is.

> Top line, even if it’s a little backgroundy, tells people to “search", second line tells people to "try”, so I don't think we want a third line telling people to “enter”, when it’s all for the same thing.

totally get it, i wouldn't have the third instance instructive/verby like that though. just a really simple descrip/definition/helper thing.

> If anything I think it would be more useful on Location, but there it would get even busier with the three toggles. 

ha, i think your busy threshold is relatively low! three toggles is not THAT bad. you're asking to put a lot of stuff in a small space, so we can either put it elsewhere or try to fit it like we're doing now (and i haven't even done that yet, so i'm optimistic). i'd rather not sacrifice usability and intuitiveness for minor space savings/de-busying, so hopefully our ultra-minimalism will be understood well enough, and if not then Help is available. 

> If your main worry is that “Mixtec etc” is too mysterious for people

it's not that it's the language is too mysterious, it's that the language AND the endo AND the glotto AND the iso are all unfamiliar. i don't recognize a single thing out of the four and there's no longer a description of what any of them are unless "search locations" is supposed to somehow explain the four concepts.

> ...and that some familiar language name would clinch it, I could see axing Glotto or ISO (let the cognoscenti figure it out) for something like this: “Try Irish, Mixtec, 台山话”. Thai instead of Irish? But we’ve got to signal and live up to this being a map focused on less common languages. Does that help?

it does! how about we do this:

```
Try Mixtec, 台山话, Thai, hait1244, loy
```

and if you're 100% anti-description and catering to the linguist power users, we at least have familiar Thai lifeline for us lowly knuckle-draggers.

**Comment by rperlin-ela** [comment]
Cool, I’m down with "Try Mixtec, 台山话, Thai, hait1244, loy”, and will submit to helper text if others think so. With all the great progress so far, this weekend (or post Week-2) could be a good time to update the team (at a very high level) and ask any questions (or just see what they say), or we could wait for till after next week.

**Comment by abettermap** [comment]
Let's omit helper text until someone besides me gets confused. The Thai thing makes it much more familiar to me though so I'm good on it for now!

I'm down for you to give the team a high-level update after we get this branch into production (I've been cranking pretty good on it today and hoping to wrap up week 2 tasks this afternoon)￼, as long as it stays high-level and we don't get 1000 suggestions on top of the new ones I/we already added with the assumption that I will complete all of them￼.￼ 

it's looking pretty badass though so I certainly wouldn't mind the feedback!￼

**Comment by abettermap** [comment]
@rperlin-ela killed it this afternoon and just pushed up what i had just now. enjoy!

got quite a few bells and whistles but it's pretty much prod-ready as-is, the only stuff i'd like to squeeze into this branch would be:

- the only real bug i found: timeline doesn't close on click (unless you clicked to a view like /Explore or /Whatever which has no timeline)
- anything w/the styling of the search boxes in the search tabs. might take some work to get Material's search input background to white. other changes shouldn't be hard though.
- smooth animated toggle of search tabs

**Comment by rperlin-ela** [comment]
Oh man, love it, you’re killing it. Provide Feedback is great, new icons are swell

Besides what you mentioned (including the Location search stunted on desktop as you probly know), the only tiny thing I see is the old circled i lingering at the top of /Info/About, maybe you’re waiting till you componentize. 

Great stuff, I feel a merge comin’ on soon…

**Comment by abettermap** [comment]
oops thought the icon was coming from wp. fixed on about and help (we don't need the addl headline now):

image

**Comment by abettermap** [comment]
k pushed up some goodies. ready to merge when you are. i have ideas about Search Locations tab. not in this PR though

**Review by rperlin-ela — APPROVED** [review]
Firing on all cylinders!

**Pull request merged**
