### PR TITLE
Census wrapup and map hover restoration

### LINKED ISSUE #207: Census panel: add dynamic legend
(originally from #202, which will need to be completed first)

Census panel: add a legend with gradient color scale, dynamic numbers that change with the language selection change, and supportive info text as needed.

very related: #203 and anything else w/census in issue title. think it through, big stuff here!

### LINKED ISSUE #224: Fix AT-driven margin issue
image

The markdown converter ALWAYS makes it a paragraph, so we end up with margins. Do something, but be careful with inline elems...

### LINKED ISSUE #230: Panel scroll improvements
- [x] Auto hide top bar
- [x] back to top button￼

**POTENTIAL**

- https://stackoverflow.com/a/39345165/1048518
- https://betterprogramming.pub/create-a-scroll-to-top-arrow-using-react-hooks-18586890fedc
- https://www.coderomeos.org/scroll-to-top-of-the-page-a-simple-react-component

### LINKED ISSUE #242: Census: remaining tweaks & fixes
...excluding the #207 stuff. 

- [x] Fix census popup text (show pretty name, not field name)
- [x] White search box like omni? would stand out much better amidst the paragraphs, and promote UI consistency.
- [x] Census popout: "view in map" goes to /Census but shouldn't it just close the popout rather than change pages?
- [x] "Clear census" link in map menu: still doing this even though it's not a toggle? seems intuitive enough in census popout so that's my vote. If including, where? below "show/zoom my loc" helper and above basemap stuff? does it need helper text? hopefully not, it's getting a little busy in the menu and "clear census XXXXX" seems sufficient if we have a good XXXXX, like _______________ 
- [x] Census dropdown: can we have smaller group headings for puma and tract? there's a lot going on in there with all that text (takes up a serious amt of space on mobile) and it seems like with all the new text in the panel we should be able to explain what the group headings currently explain, but above or below the dropdown?
- [x] Fix hover issue which causes census poly's to oil-spill
- [x] Include Ross's new top/bottom UI text in Census panel

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #230 
- Fixes #242
- Fixes #207 
- Fixes #224 (close enough anyway)
- Adds tooltips and hover behavior
- Improves polgyon symb and selection style

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela went down the panel auto-hide back-to-top rabbit hole again and came out reasonably victorious. some quirks for sure and pretty challenging to figure out, but internet came to the rescue-ish.

i think it's pretty smoove (definitely try on mobile!) but if you have any issues, worst-case we can just preserve the back-to-top btn and scrap the top bar auto-hide. but i've tested it a fair amount and the quirks are worth it so far.

will get on the census stuff tonight or tomorrow...

**Comment by rperlin-ela** [comment]
Very smoove, what's not to love? Seems to disappear on me when I scroll to the very bottom, but definitely a plus!

**Comment by rperlin-ela** [comment]
Looking real good to me. I'll be on the move now till mid-pm but can merge, test, zoom etc after that

**Comment by abettermap** [comment]
Ross-

friggin' beauty, really proud of this branch! holler if any serious issues otherwise i'm ready to merge.

**Review by rperlin-ela — APPROVED** [review]
Loving every moment

**Pull request merged**
