### PR TITLE
Panel tweaks

### LINKED ISSUE #250: The word "table" on the Data panel
Tiny pet peeve here, but when the Data table opens up "full screen" I still see and can't quite unseen the word "table" behind it back on the panel itself. Any word to axe it or make it read "Data"?

### LINKED ISSUE #251: Panel titles: show for all views
It's annoyingly inconsistent to see some blank headings (and the lack of plurals mentioned in #204), so i'd like to see something for all of them, e.g.

image

image

actually i think those are the only two we're missing?

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #251
- Fixes #250

bits of #204 and maybe others. and more not documented anywhere, just lots of standardization of panel headings and intro's.

### CODE REVIEW

**Comment by abettermap** [comment]
also have a look at my commit messages to get an idea of what i did since the closed issues don't cover it entirely: https://github.com/Language-Mapping/language-map/pull/253/commits

**Comment by rperlin-ela** [comment]
All looking pretty nice — gotta run, but I think just "Language" instead of "Language Profile" for consistency now that I understand your strategy? And I'm not totally sold on Community Profile and the icon, gotta think about that one, maybe something more around Site. And I saw your other note— does that mean you'd advocate for "Home" instead of "Languages of NYC", which is not that descriptive? But let's merge for now!

**Review by rperlin-ela — APPROVED** [review]

**Comment by abettermap** [comment]
i'll get back to you on the comment, merging for now

**Comment by abettermap** [comment]
> just "Language" instead of "Language Profile" for consistency now that I understand your strategy? 

Sure that works. I guess would say "Language" from the perspective of arriving via _/Explore/Language_, but elsewhere like /Explore/Town/Something/Language maybe "Language Profile"? I mean I'm only doing one title regardless of where user came from, but UI-wise I still see /Explore/Something/Stuff/Language as a different thing than /Explore/Language/Stuff, even though they show the same thing. 

On that note, why are we doing that? I'm pretty confused why we have both of those route depths. Is it in order to preserve the timeline breadcrumbs nav stuff so user can climb back to where they came from via "up one level" or timeline, etc.? If not, why do we have /Explore/Something/Stuff/Language at all instead of just /Explore/Language/Stuff? There's a fair amount of code to handle the difference, so just wondering why we did it this way. 

> And I'm not totally sold on Community Profile and the icon, gotta think about that one, maybe something more around Site.

Sure thing, I'm not wed to what I made, just going off of how we refer to it elsewhere, e.g. "no community selected". 

So, whatcha got for icon and text?

> And I saw your other note— does that mean you'd advocate for "Home" instead of "Languages of NYC", which is not that descriptive? 

Meh I'd take that over Home. But that over "Discover NYC Languages" or "Search & _______" with a human-friendly term for "symbolize" to fill in the blank. 

Pretty open to whatever, and yeah "Home" sucks, it's even less informative than "Explore" as a panel title. deviating from "Home" throws off the consistency of the rest, but seems worth it here. User just arrived, of course they're home!

I'm game for whatever you think on the panel titles and icons (if you are ok with adding one to Home, awesome, that's our only icon-less straggler). my main thing is that we have a title for every panel instead of a gaping green void, which I think we've now... aVOIDed.

**Comment by abettermap** [comment]
As for a "Community Profile" replacement, we've been internally referring to it as Details forever, so maybe "Site Details"?

**Comment by abettermap** [comment]
...and then either Language or Language Details for the parent?

**Comment by rperlin-ela** [comment]
> Sure that works. I guess would say "Language" from the perspective of arriving via _/Explore/Language_, but elsewhere like /Explore/Town/Something/Language maybe "Language Profile"? I mean I'm only doing one title regardless of where user came from, but UI-wise I still see /Explore/Something/Stuff/Language as a different thing than /Explore/Language/Stuff, even though they show the same thing.

Good point, agreed. If we're doing just one across the board, let's go with Language.

> On that note, why are we doing that? I'm pretty confused why we have both of those route depths. Is it in order to preserve the timeline breadcrumbs nav stuff so user can climb back to where they came from via "up one level" or timeline, etc.? If not, why do we have /Explore/Something/Stuff/Language at all instead of just /Explore/Language/Stuff? There's a fair amount of code to handle the difference, so just wondering why we did it this way.

Good question, and I don't know if I can unearth the ɑnswer completely. Definitely connected to the fact that all the other categories are just ways into the languages, so preserving breadcrumbs might be part of it, not sure if cards and card footers are also involved since I've lost track of how those are fed. Simplicity and consistency would be great, but assume it's not worth trying to get to the bottom of or unwinding at this point...

> Sure thing, I'm not wed to what I made, just going off of how we refer to it elsewhere, e.g. "no community selected".

Speaking of this, wouldn't it be consistent to have an Explore header on "No community selected", or did you deliberately leave that one case blank? Likewise when you select a random community, it goes to a Details page without an Explore panel header. Same thing when I go to anything from the Data table "details", doesn't have a header. And then it's like anything you do from there doesn't have a header because you didn't come via Explore. Not a big deal, just asking about these various other cases

> Meh I'd take that over Home. But that over "Discover NYC Languages" or "Search & _______" with a human-friendly term for "symbolize" to fill in the blank.

Oh yeah sorry I had missed your idea before to use "Search and Display" or "Search Language Sites" for the Home panel heading. "Search and Display" is pretty good, or "Search and Display Sites" if that's not too long and unintuitive. I guess we just can't get consistency with panel icon text, which we otherwise kinda stick to. And what about having a non-home icon up there, wouldn't be confusing? The obvious candidate would be the magnifying glass... I need to sleep on this whole bit, but tell me what you think

> As for a "Community Profile" replacement, we've been internally referring to it as Details forever, so maybe "Site Details"?

Site Details is pretty good. But any chance then I could ask you to change "Locations" to "Sites" in that page next to the pin in the circle? And I guess then also in the Locations/Neighborhoods pop-up. I know we use it for "local community data" in the table, but could that same pin in the circle be our icon for "Site Details"?

Side-note: did we decide to axe having the panel icon you're on not be highlighted? I kind of miss that Now that we have all these different headings it feels relevant again, maybe

**Comment by rperlin-ela** [comment]
> could that same pin in the circle be our icon for "Site Details"?

Whoops, sorry, already in use for Neighborhoods

**Comment by abettermap** [comment]
> wouldn't it be consistent to have an Explore header on "No community selected"

did this intentionally if that's what you mean:

image

Info, Home and Census panels also do not have a header, i think it's fine. and i wouldn't know what to make the header w/o being redundant since "No community selected" is already the panel title bar.

> Likewise when you select a random community, it goes to a Details page without an Explore panel header.

not sure what you mean? e.g. i see this when i click Show Me Random btn:

image

> Same thing when I go to anything from the Data table "details", doesn't have a header. And then it's like anything you do from there doesn't have a header because you didn't come via Explore.

are you referring to this?

image

if so, i couldn't care less what the panel is behind it. i only see it on large monitors, not on my phone or laptop: 

image

> Same thing when I go to anything from the Data table "details", doesn't have a header. And then it's like anything you do from there doesn't have a header because you didn't come via Explore.

again, almost the entire application is based off of routes (the URLs), so i'm adding overrides for these silly little scenarios. if it were up to me we would have **a full-screen table for all screen sizes**. it feels unnecessary and awkward to have to scroll on a 23" monitor that would otherwise show the data just fine w/o scrolling. i understand why we did that since the comfort of knowing the map is still back there is semi-nice, but not as nice as not having to scroll would be! not to mention not having to do all these overrides for things that only people on wider screens see.

so, **can we just make the table fullscreen for all users**? they have the universal-close "X", and the table slides up from the bottom and you can still see the map on the way in. they'll be fine.

> And what about having a non-home icon up there, wouldn't be confusing? The obvious candidate would be the magnifying glass...

would it be so bad for the "Home" panel if we did these?

- call it "Search" in the nav tabs. i know searching is available everywhere now, but it's also available in Home, so it's technically accurate if we label the nav tab as Search.
- give it a different (but similar) icon to that of the magnify glass. there are [plenty](https://react-icons.github.io/react-icons/search?q=search). i kind of like _BiSearchAlt_ and _HiOutlineSearchCircle_, although the "backwards" direction of the latter bugs me, so maybe _IoSearchCircleOutline_.
- panel title would be  "Search and Display Sites" or whatever we settle on, and include the search-like icon

> I know we use it for "local community data" in the table, but could that same pin in the circle be our icon for "Site Details"?
> Whoops, sorry, already in use for Neighborhoods

thousands of icons to choose from. hit me!

oh and i made your other change suggestions as well.

**Comment by abettermap** [comment]
sorry forgot this

> Side-note: did we decide to axe having the panel icon you're on be highlighted? I kind of miss that, and now that we have all these different headings it feels relevant again, maybe

yes, not sure what happened, will look into

**Comment by rperlin-ela** [comment]
> did this intentionally if that's what you mean:
> 
> image

Cool

> 
> Info, Home and Census panels also do not have a header, i think it's fine. and i wouldn't know what to make the header w/o being redundant since "No community selected" is already the panel title bar.
> 
> > Likewise when you select a random community, it goes to a Details page without an Explore panel header.
> 
> not sure what you mean? e.g. i see this when i click Show Me Random btn:
> 
> image
> 
> > Same thing when I go to anything from the Data table "details", doesn't have a header. And then it's like anything you do from there doesn't have a header because you didn't come via Explore.

This is all good now, not sure why I didn't see it before. All good.

> 
> are you referring to this?

No, I meant going from Data to Explore via "full-page details" but it all seems fine now!

> image

Didn't mean this— I'm happy with this.

> so, **can we just make the table fullscreen for all users**? they have the universal-close "X", and the table slides up from the bottom and you can still see the map on the way in. they'll be fine.

Sure, let's do it!

> would it be so bad for the "Home" panel if we did these?
> 
> * call it "Search" in the nav tabs. i know searching is available everywhere now, but it's also available in Home, so it's technically accurate if we label the nav tab as Search.
> * give it a different (but similar) icon to that of the magnify glass. there are [plenty](https://react-icons.github.io/react-icons/search?q=search). i kind of like _BiSearchAlt_ and _HiOutlineSearchCircle_, although the "backwards" direction of the latter bugs me, so maybe _IoSearchCircleOutline_.
> * panel title would be  "Search and Display Sites" or whatever we settle on, and include the search-like icon

I think this is right, and will get us to consistency. I like all three. Search, _IoSearchCircleOutline_, Search and Display Sites. I know you're attached to that Home icon in the top left of other panels tho

> thousands of icons to choose from. hit me!

For Site Details icon, could we break out _MdPlace_ or _FaMapMarkerAlt_ or similar?

**Comment by abettermap** [comment]
too small:

image

backup plan? BiSearchAlt is weird too

image

as is HiOutlineSearchCircle

image

i think anything w/an outline like that is a no-go.

IoSearchOutline is good:

image

...but haha:

image

i don't think this would be the end of the world:

image

>  I know you're attached to that Home icon in the top left of other panels tho

i'm attached to _something_ being there. i definitely use the button, and it looks silly with a centered title in the bar and nothing on the left.

roll with that last one then?

**Comment by rperlin-ela** [comment]
ok I guess IoSearchOutline (change tooltip too?) and roll with that last one. Little weird in the timeline in case you have any thought on that, my vote might just be to cut Home out of the timeline altogether, but I won’t die on that hill, as they say

**Comment by abettermap** [comment]
ha i use that one a lot too! so the pattern is basically you just don't want the user to have any way to get back to the place they started from except the bottom nav and the semi-secret logo click? i don't just don't interact with the app that way or see it that way, and i strongly disagree with limiting the options for returning to The Origin of All Experience. i'm not a UX pro so i'll admit to being wrong if i am, but this has concept has come up like 65ish times and i'd really like a third opinion. 

i see the world like this:

```jsx
<Building type="house">
  <Room type="living-room">
    <Wall>
      <Window direction="north" height={42} width={27} />
      <Window direction="north" height={42} width={27} />
      <Painting />
    </Wall>
  </Room>
  <Room type="kitchen">
    <Appliance type="stove" isGas>
      <Burner position="front-right" isPrimary />
      <Burner position="front-left" />
      <Burner position="rear-left" />
      <Burner position="rear-right" />
    </Appliance>
  </Room>
</Building>
```

there is no such thing as 

```jsx
<>
  <Room></Room>
  <Room></Room>
  <Room></Room>
  <Room></Room>
</>
```

Form and Void. With and Without. Structure surrounds our existence. 🤯

**Comment by abettermap** [comment]
> so, can we just make the table fullscreen for all users?

scrapping this hard. wasted an hour or at least it felt like it. table = nightmare for styling.

**Comment by abettermap** [comment]
>  (change tooltip too?) 

i went with "Search & Display Options" but i can change to match the heading if you want. no strong feels on that one.

**Pull request merged**
