### PR TITLE
Sow3.wording and UI

### LINKED ISSUE #183: Minor wording changes
Change the written copy for the following items (specific text may already be indicated in a separate spreadsheet):

1. “Details” view: improve default text when no community is currently selected. If needed, perform basic style edits (_Any slight improvements in styling, even like bolding, to make it look less like an error page?_) to accommodate the change: _Please select a community by clicking a point on the map, searching for a language from Home, or specifying a community in Data._ 
2. Census language search box: change default placeholder text to “Choose a language or start typing here”.
3. Explore/Neighborhood/Language view: use the same introductory text as that of /Explore/Town/Language.

### LINKED ISSUE #184: Add/restore missing UI bits
- [ ] “Details” view: show Macrocommunity as a clickable, linkable “chip” in the same manner as existing chips such as World Region.
- [ ] Colored circle for "World Region" no longer appearing in UI table (migrated from #174)
- [ ] “Details” and “Language profile” views: for ASL, Avestan, Mongolian, or any Language with an image for its endonym, include English name below the image (consistent with all other text-only languages).

### LINKED ISSUE #185: "Status" legend items: include descrip/label
- [x] “Home” view: “Status” legend: support descriptive blurbs via Airtable in the same manner as that of the legend for the “Size” symbology. May require some AT adjustments.
- [x] Remove `queryFields` from code after confirming obsoletion.

### LINKED ISSUE #186: “Share” buttons: indicate language in post title/body
“Share” buttons: in the post title, if possible and relevant, specify the language specific to the link being shared. Currently this is working for Twitter but not Facebook or LinkedIn, and the status of Reddit is unknown. If it is not possible to achieve this then some indication of the selected language will be made in the body of the post when possible (LinkedIn may not support this), e.g. “Chakhar Mongolian [language] is spoken in Sunset Park (Brooklyn) [location]. Part of an interactive map...”

### LINKED ISSUE #187: "Label by": allow change during "Show by: None"
(not really a bug but sort of)

“Home” view: restore support for “Label by” interaction when “Show by: None” is set. 

**Near-Future Jason:** there's a commit with JUST this. Figure it out from there.

### PR DESCRIPTION
**Pull request by abettermap**
## Summary
Fixes SOW 3.1.1 and 3.1.2 except for 3.1.6, aka #187 

## Issues resolved by this pull request

- Fixes #183 
- Fixes #184
- Fixes #185
- Fixes #186
- Fixes #187

### CODE REVIEW

**Comment by rperlin-ela** [comment]
Everything looks good, just a few things:

- Explore/Neighborhood itself should not have "Languages with a significant site in this neighborhood..." at the top. Only Explore/Neighborhood/Nabe Name
 
- Happened to catch that Avestan, when shared, is called "undefined". Not sure why since Mongolians are fine, hopefully no others but not sure how to check. If we can't get it to say Avestan, better for it to say nothing.
 
- Sharing via LinkedIn and Facebook brings up (as a "preview") an ancient, weirdly specific screenshot (like SOW 1), no matter which community is being shared. Maybe they're the only two that do that, but is there any way we can feed them or get them to pull an updated screenshot? A LinkedIn share has no text, so if we can't at least update the preview image, I think we're better off axing LinkedIn altogether. (Tested Reddit, seems fine.)

**Comment by abettermap** [comment]
Thanks for reviewing, I'll fix Neighborhood and look into Avestan tomorrow, sounds weird if Mongolian works so it's gotta be easy! 

I'm also going to remove "Show by: None" from the dropdown for now, will comment a bit in email. It shouldn't affect the upcoming census toggle. 

As for LinkedIn, I'm giving it all the properties it accepts, and the main one is same as Twitter so if that's not doing anything then I'd say axe. 

As for screenshots, to make them dynamic would require a server and some heavy coding, maybe up to a week of work. You do have control over _which_ screenshot gets used though, and it is documented "somewhere". It's in our other GH repo (the one called "config") if that rings any bells? If not and you'd like to know how to change it, let me know and I'll point you there tomorrow, it's just a couple steps I believe.

**Comment by rperlin-ela** [comment]
Sounds good — don’t need dynamic, just a decent up-to-date screenshot. Enthusiastically going to the config repo, which rang about zero bells, I went and subbed in a new screesnhot in the most basic and simplest way I could see, don’t see any effect yet and not sure if that will do the trick or break everything

**Comment by abettermap** [comment]
Which file/s? There's one called fb.png and twitter.png in the _img_ folder. 

Might be cached server-side on fb and LinkedIn. Been my experience. 

If you've changed both files and you commit them in GitHub and try in an Incognito window and still see no change, I'd bet cache so in that case sleep on it and wake up to hopefully glorious new screenshot 🌅

**Comment by rperlin-ela** [comment]
Yup, replaced those two — LinkedIn reflecting the change, not yet FB but I assume the bright new day is coming soon, so let’s say case closed

**Comment by abettermap** [comment]
Nice work, and you added the steps to The Manual™ right? 😃 

I'm not seeing FB either. Here's a handy tool to see what their crawler sees: https://developers.facebook.com/tools/debug  (also good for manual gold)

It's getting the correct URL to the image, and when I open the image in a new tab it's definitely the new one. So it's gotta be caching. Case closed!

Will let you know when I've pushed the other changes and we can wrap up this branch.

**Comment by abettermap** [comment]
> Happened to catch that Avestan, when shared, is called "undefined". Not sure why since Mongolians are fine, hopefully no others but not sure how to check. If we can't get it to say Avestan, better for it to say nothing.

I can't reproduce this. Is it happening from a certain page? This is what I see in Details in the deploy:

image

image

**Comment by rperlin-ela** [comment]
Nor can I now! But I think I must have been on the site, not the deploy— so maybe #184 fixed it. Anyway rock and roll.

**Review by rperlin-ela — APPROVED** [review]

**Comment by abettermap** [comment]
@rperlin-ela I pushed up the big fat fix for #187 so give the deploy a test when it's ready and respond to the comments in that issue please. Gold, Jerry, gold!

**Comment by abettermap** [comment]
@rperlin-ela merging! Open/re-open any issues if needed

**Pull request merged**
