### PR TITLE
Post rel bug fixes

### LINKED ISSUE #278: ChunkLoadError: Loading chunk 3 failed.
Should either just remove the React.lazy and webpack chunk, or fix it. [Looks like a good article](https://medium.com/@botfather/react-loading-chunk-failed-error-88d0bb75b406)

Sentry Issue: [LANGUAGE-MAPPING-4R](https://sentry.io/organizations/endangered-language-alliance/issues/2340824935/?referrer=github_integration)

```
ChunkLoadError: Loading chunk 3 failed.
(error: https://languagemap.nyc/static/js/table.9c943521.chunk.js)
  at None (https://languagemap.nyc/:1:3567)
  at None (components/App.tsx:31:5)
  at None (/static/js/4.f3d2944a.chunk.js:2:2162770)
  at gs (/static/js/4.f3d2944a.chunk.js:2:2162918)
  at ul (/static/js/4.f3d2944a.chunk.js:2:2154670)
...
(14 additional frame(s) were not displayed)
```

### LINKED ISSUE #280: Feedback form size
Feedback from users:

“Your feedback form element is not working properly. I had to go in and edit the code from my browser to resize it—not sure why it is currently set to a height of only 48px but something closer to 1000px is probably what you want."

"Your provide feedback popup is broken, having 0 height, I literally had to inspect element to adjust the size of this form"

### LINKED ISSUE #282: TypeError: null is not an object (evaluating 'window.localStorage.getItem')
iOS Safari or maybe everybody (???) has no `window.localStorage` presumably.

Sentry Issue: [LANGUAGE-MAPPING-5F](https://sentry.io/organizations/endangered-language-alliance/issues/2343939206/?referrer=github_integration)

```
TypeError: null is not an object (evaluating 'window.localStorage.getItem')
  at T (/static/js/main.b0031bdf.chunk.js:1:196343)
  at Zo (/static/js/4.f3d2944a.chunk.js:2:2115730)
  at gs (/static/js/4.f3d2944a.chunk.js:2:2162137)
  at ul (/static/js/4.f3d2944a.chunk.js:2:2154670)
  at sl (/static/js/4.f3d2944a.chunk.js:2:2154595)
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by abettermap**
- Fixes #282 
- Fixes #278 
- Fixes #280

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela  YIKES!!!

tonssss of people evidently have cookies disabled. so need to test/merge pronto.

**Comment by abettermap** [comment]
here's how to check:

Go to `chrome://settings/cookies` in Chrome

turn this on:

image

go to the map and see if it loads and that the welcome footer has no checkbox and neither does Settings

**Review by rperlin-ela — APPROVED** [review]

**Comment by abettermap** [comment]
for the chunk thing i can't reproduce it but i removed my best guess. only thing you could try is turn off LTE and Wifi on your phone so it only uses 3G

**Comment by abettermap** [comment]
test on prod as soon as it merges! i'll do the same. make sure to set your cookies back, otherwise hardly anything works in the browser.

**Comment by abettermap** [comment]
i'd say we defeated the chunk and localStorage problems. buncha users down to 0 in the past couple days:

image

web merc is alive and well though, gonna look into it today:

image

**Pull request merged**
