### PR TITLE
Render IPA chars consistently

### LINKED ISSUE #84: Correctly show IPA characters in UI
## Description

14 endonyms that contain IPA characters are displaying awkwardly in Gentium. We want to use Google Noto Sans Regular for those 14 to get a better display. Fonts are listed in the UI_Fonts tab on this sheet: https://docs.google.com/spreadsheets/d/1QfySFNpD2VnLand3-lTNAPAlrm0Cmv9As01LAXgXC0E/edit#gid=2111360179

We want a setup, as we have endonyms, where this list can be maintained and changed by ELA, automatically updating the UI with Noto font instead of Gentium for relevant items.

### PR DESCRIPTION
**Pull request by abettermap**
## Issues resolved by this pull request

- Closes #84

### CODE REVIEW

**Comment by abettermap** [comment]
@markturin @fiddleHeads @rperlin-ela 

In case you need the "logo" for anything, I created an actual image for it (it was just HTML before). Couple variations: https://github.com/Language-Mapping/language-map/tree/master/public/img/logo

Before anyone asks for adjustments, the answer is a polite No. I was actually hoping YOU would provide ME with a logo that I could use as a basis for color schemes and other image stuff (app tiles, favicon, etc.). So, if you have any designer connections who would like to sign up for that, [here is a source file](https://github.com/Language-Mapping/language-map/blob/master/src/img/logo.svg) they could start from (or make their own, even better).

The "source" file is what I'm actually using in the UI (the PNGs are just for your use if you need them) and it's composed of several individual parts that can be separately and dynamically customized via code (e.g. the accent line and text colors in the Welcome screen are different from those in the 24/7 logo, even though they're using the same source image). This opens up some fancy doors for extra bells and whistles like animating individual parts. Bonus UI points for those little tweaks! 🏆 

Will note that on my ever-growing wishlist.

**Comment by markturin** [comment]
Many thanks for this, and just to say I do have a student who is a trained graphic designer, I’dd be very happy to bring her into this conversation and get her working on a logo or WordMark if you would like that, so please do let me know (Ross?). Not so sure how comfortable she would be getting in to GitHub but its not too hard, but she is a really calm and focused designer who listens carefully to what people need, and I have some money to pay her.

**Comment by abettermap** [comment]
Thanks Mark, that would be great. Please introduce us in a group email, no need for GH, I can handle that part, it was just an easy way to share the source file I created.

**Comment by markturin** [comment]
﻿Will do! Thanks. Might take a day or two. Heavy start to the week. Kindly Mark

**Comment by rperlin-ela** [comment]
This is great, thanks!

**Pull request merged**
