### PR TITLE
Table fixes/improvements

### LINKED ISSUE #156: Clickable "Size" and "Status" in UI Table
## Description

This is a tiny thing, but given the great click-to-filter capability with all the columns (obviously except Global Speakers) I would expect the same with Size and Status. Apologies if there's some reason we decided against this long ago that I've forgotten. If in agreement, only fix if this is a very simple and quick thing! Otherwise totally fine as is, feel free to close issue and ignore.

### LINKED ISSUE #158: Table export: additional requests
_Originally posted by @rperlin-ela in https://github.com/Language-Mapping/language-map/issues/118#issuecomment-756193122_

A few more:

- [x] - Prevent "Global Speaker Total", if empty, from displaying in PDF as 0
- [x] - Prevent comma or other random mark from appearing where there's a missing endonym, e.g. Chinese (Mandarin), Coptic, Bantawa etc
- [x] - "Location" instead of "Primary Location" to match UI Table?
- [x] - Space after the comma where there are multiple countries
- [x] - Switch "full source dataset" link from Sheets to https://airtable.com/shrqQo5FJHvhKtffs

### PR DESCRIPTION
**Pull request by abettermap**
## Issues resolved by this pull request

- Fixes #158  
- Fixes #156

@rperlin-ela Also hopefully fixes-ish the table Country click issue once and for all. It wasn't fully resolved: if you click on a Country cell but not _directly_ on it, like a little above or below the value, it breaks. My "solution" ultimately was to just jump ship if there's nothing there instead of the whole app crashing. For fat-fingerers it will just feel like nothing happened so they'll click again, hopefully _on_ the value or flag this time. 

I'm sure there's some kind of styling fix but not worth it given the headaches from this column already, and it's an edge case (literally 😆 ) anyway.

The Country cells have been a total nightmare because they not only contain more than just text, but their source is an array while the table filter column expects text. So many levels of 🤬 . Try in prod to see what i mean then try in deploy to confirm it's fixed, please. Along w/all the exporting stuff.

### CODE REVIEW

**Review by rperlin-ela — APPROVED** [review]
Looks good. We lost all non-Roman characters in the Endonym column— Greek, Cyrillic, and some others that used to come through— but I guess it's better to be consistent in that respect for now

**Comment by abettermap** [comment]
internet to the rescue. was able to squeeze a few more endo's out. poor Northern Africa, still empty as ever!

let me know if it works and we can merge

**Comment by abettermap** [comment]
also, do you think instead of empty values there should at least be "uh ohhhh, does not compute, friend-o!" or N/A or something? it's kinda misleading leaving it blank, especially when it's in the table

**Comment by rperlin-ela** [comment]
Good endonym-squeezing! 

Some kind of notice would definitely be good— whatever is most doable or makes sense from your end. Ideally some kind of bold sentence at the top like *For non-Roman characters support, export as CSV or use full dataset and then an asterisk instead of the empty values? Without a sentence at the top I’m less sure how to communicate this, but I’m open

**Comment by abettermap** [comment]
oh i mean in the cells themselves, not the page title. that makes sense too, enough that i already put it in the issue 😆 : https://github.com/Language-Mapping/language-map/issues/118#issue-723812769

emphasis on this part:

image

didn't mean to open a can of worms there. if you want something besides blank cells, i'm willing, but adding text to the page takes time and is difficult to do properly.

**Comment by rperlin-ela** [comment]
I understand, it’s a good idea, just saying I’m not sure it’s going to be clear without such a sentence. If you think it’s an improvement and it’s quick, let's try an asterisk or a hyphen (in the cells) instead of a blank, otherwise just as is.

**Comment by abettermap** [comment]
> *For non-Roman characters support, export as CSV

i'm actually prepping the data the same way for CSV, but users can hit Airtable for the full.

speaking of, what if we left the missing Endo cells empty and just changed the title? (pretend it's centered):

image

**Comment by rperlin-ela** [comment]
Nice— let’s do that, but probably don’t need endonym in there, just “includes non-Roman characters”

**Comment by abettermap** [comment]
trying to avoid more netlify builds today so just let me know if this is good before i push and deploy again:

image

**Comment by rperlin-ela** [comment]
bingo, good to go

**Comment by abettermap** [comment]
cool, give it a try and then i think we're done w/table yeah?

**Comment by rperlin-ela** [comment]
Done!

**Pull request merged**
