### PR TITLE
No MB boundaries (Neighbs only so far)

### LINKED ISSUE #217: Neighborhoods: separate and de-Boundariesize
This is going to affect a lot of things, but I'll try to keep as little in this branch as possible before moving on to census stuff.

## Data
- [ ] add neighborhoods ~~and counties layers~~ **just neighbs in this issue** from our own custom tilesets as separate, distinct layers
- [ ] rm all instances and refs to MB Boundaries, including lookup tables

## Controls
- [ ] ~~below the 2D/3D btn, add a `...` btn that triggers a popout containing the "show/zoom my location" and (for now at least) the Counties toggle.~~ PENDING
- [ ] ~~if needed, include neighborhoods toggle in that menu as well.~~ PENDING
- [ ] ~~either way, add neighbs toggle to /Explore/Neighborhoods and /Explore/Neighborhoods/Something~~ MOVED to #225 

## Behavior
probably won't get ALL the stuff we discussed in this branch, but ~~counties and~~ **JUST COUNTIES in this branch** neighborhoods will ~~both~~ still:

- [ ] zoom to selection on click
- [ ] make bg color of selected polygon stand out symbology-wise from the others
- [ ] popup: just the name for now. bells whistles later.

Can get all fancy with the routing and highlighting in another branch. Big stuff here is just to start using our own layers.

### PR DESCRIPTION
**Pull request by abettermap**
Fixes #217

Most of neighborhood stuff is now free of MB Boundaries. It's hard-coded though, so census and county stuff will need to be adapted/added in another branch so we can stop straddling the neighborhoods AT stuff.

Only things hopefully left to do in neighbs (new issue!):

1. move toggle out of Search Locations into /Explore/Neighborhood and one level deeper
2. support auto zoom on initial page load when starting from something like /Explore/Neighborhood/Astoria.
3. for /Explore/Neighborhood/Something with no primary langs (???), rm the preceding text before where the cards would normally be.
4. support intro text from summary field in AT
5. show borough as subtitle in /Explore/Neighb/Something

### CODE REVIEW

**Comment by abettermap** [comment]
@rperlin-ela deployed a WIP. status:

- remember only Yorkville will work. if you want to try The Big Switch, go for it. i'm pointing the code to the proper column so no changes there.
- i can't get the auto-zoom to happen on the _first_ visit to Yorkville. everything else is fine, including popup and highlight on first visit. 
- close btn "X" working nicely on all popups
- symbology is probably semi-garbage since i don't have the outlines back in yet.
- no counties, and no census clicks yet. you wouldn't believe how complicated it was just to get neighborhoods working 📈 
- i forgot to turn off neighbs by default, left it on for testing simplicity. will turn off before merge (remind me!)
- neighbs is drawing on top of the points. also complicated but will fix.

what is the bare min when we can merge this? i know there's some fixes to be made for sure, but it's hard to test with only one functioning neighborhood. i'll make the fixes a top priority after we merge (and before i even think about counties and census), so let me know how low your temporary standards can go. :)

**Comment by abettermap** [comment]
if it matters, the lack of outlines and the accidentally turned on by default thing should both be easy fixes. draw order... ish.

but the incorrect behavior on first visit is going to take time, already been banging my head on it for awhile

**Comment by abettermap** [comment]
also, first time i've tried this, but going to yorkville via /Explore instead of map click is interesting. i kinda like how it still shows a popup without turning on the layer. less orange sea distractions.

**Comment by abettermap** [comment]
(oops, meant to include "with Neighborhoods turned _off_"

**Comment by abettermap** [comment]
this definitely no longer feels like it belongs here, and same with counties:

image

/Explore/Neighborhoods and /Explore/Neighborhoods/:something

...would be my vote for a toggle

**Comment by abettermap** [comment]
ha i see you've made the switch already. although now it's not working, including yorkville. hmmm weird. data looks ok

maybe it's because the "name" is not unique in MB since i haven't changed it yet

**Comment by abettermap** [comment]
i made those changes just now in Studio Dataset. will still have to wholesale replace to remove the coords columns, but it's not hurting anything at the moment.

the new tileset will be generated shortly. i doubt it's that easy a fix, but we'll see. i've definitely had problems in the past when there's a non-unique identifier field

**Comment by abettermap** [comment]
well that's a bummer, auto-zoom was working great for yorkville, but the new changes make it not work for any of them. it can't be the coords though, since the popup place comes from those and is correct

tomorrow....

**Comment by rperlin-ela** [comment]
Ok, sounds good, had to pull the bandaid off. More tomorrow, but looking like real progress.

Anyway, I’ll play around more first thing in the morning, and hopefully the big switch gives us more to play with. Sorry auto-zoom’s been a tough nut ot crack. But it’s starting to feel de-boundariesified for real, I could just see it making sense to solve what’s in your bullets anyway before merging, and maybe also getting “summary” in there towards the front burner. And getting the Murray Hills and Sunnysides in sync.

**Comment by abettermap** [comment]
That's all, huh? Anything else? 😆

**Comment by abettermap** [comment]
So basically get everything in the scope working for neighborhoods before we merge, with only one polygon to test on? Would be nice to make a slight concession on that if you can.

**Comment by abettermap** [comment]
If the auto zoom is critical to production, I think that answers our question about when we need a toggle for it. Seems like no based on this?

**Comment by abettermap** [comment]
Auto zoom IS working. but it's not until a neighborhood has already been visited once. I didn't notice it and assumed it was only an on load thing because I only had yorkville to work with. 

This should help with troubleshooting, and obviously I'll fix, but hopefully it will give you enough of an idea on the auto zoom and popup behavior in the interim. Works via Explore or the map, just have to have gone to the neighborhood once first.

**Comment by abettermap** [comment]
One more thing, it looks like the thing we were worried about with /Explore/Neighborhood is not an issue (as in cards might show up for neighborhoods that have no languages). I must be querying it for only the neighborhoods that have primary languages, so a happy surprise and one less thing to address￼￼.

**Comment by rperlin-ela** [comment]
> So basically get everything in the scope working for neighborhoods before we merge, with only one polygon to test on? Would be nice to make a slight concession on that if you can.

I think I'm just confused about where things are at: what the Big Switch affected and why, why Yorkville is different from anything else now post-Big Switch, and other things.

But if merging at this point will really help you keep up the momentum, let's do it. Just turn off Neighborhoods by default and restore the borders between them.

> If the auto zoom is critical to production, I think that answers our question about when we need a toggle for it. Seems like no based on this?

Yeah that's fine, no toggle

> this definitely no longer feels like it belongs here, and same with counties:
> 
> image
> 
> /Explore/Neighborhoods and /Explore/Neighborhoods/:something
> 
> ...would be my vote for a toggle

Sounds good

**Comment by abettermap** [comment]
Yorkville isn't different, I was mistaken. Same behavior for all neighborhoods. Will fix all ASAP￼

**Comment by abettermap** [comment]
## Remaining before merge (???)

> I could just see it making sense to solve what’s in your bullets anyway before merging

thought we agreed we could merge before this one:

> no counties, and no census clicks yet.

...and that we would just focus on neighborhoods for this branch? counties + census will take a couple days.

## Review

ready to go. just be sure to read the PR above. got about half a day today into trying to make the auto-zoom work on both the initial view (probably most users aren't _starting_ from /Explore/Neigh/Astoria though, so not critical relative to other priorities) and routes, and several hours last night. no promises the code won't start anyone's device on fire, it's NUTS.

**Comment by abettermap** [comment]
sorry Ross, forgot to push, deploy on its way

**Review by rperlin-ela — APPROVED** [review]
Cool, onward

**Comment by abettermap** [comment]
Nice, whatever changes you need to do in Airtable, if any, to make neighborhoods ready for production, go ahead, it will be built shortly.￼

**Pull request merged**
